import {AbsoluteFill, Sequence} from 'remotion';
import type {AnimationManifest} from './model';
import {createSceneArtDirection} from './visual-system/grammar';
import {VisualScene} from './visual-system/VisualScene';
import {DEFAULT_VISUAL_PRESET_ID} from './visual-system/preset';

const items = [
  {copy:'AI KHUẾCH ĐẠI\nCÁCH TA\nSUY NGHĨ.', semanticFunction:'thesis declaration', semanticArchetype:'thesis-declaration' as const, semanticObject:'none' as const, concept:'A thesis becomes a field of intellectual weight', object:'editorial typography', rationale:'No object: the declaration itself is the strongest honest visual.', tension:'Amplification can sharpen or distort the thinking already present.', emphasis:'KHUẾCH ĐẠI', support:[], improvement:'Overscale type, crop and active counter-space create a poster without decorative objects.', reuse:'Reusable for any thesis whose language itself is the memorable image.'},
  {copy:'NHANH HƠN\n→\nRÕ HƠN', semanticFunction:'contrast before after', semanticArchetype:'contrast-before-after' as const, semanticObject:'balance' as const, concept:'Speed and clarity occupy visibly unequal states', object:'material balance beam with unequal masses', rationale:'A physical imbalance makes the non-equivalence between two desirable outcomes immediate.', tension:'Two positive qualities are often mistaken for the same outcome.', emphasis:'RÕ HƠN', support:[], improvement:'The contrast is felt through weight and instability instead of two labelled cards.', reuse:'Reusable for trade-offs, false equivalences and before/after arguments.'},
  {copy:'TÍN HIỆU NÀO\nCHƯA ĐƯỢC\nKIỂM TRA?', semanticFunction:'investigation verification', semanticArchetype:'investigation-verification' as const, semanticObject:'lens' as const, concept:'Verification isolates one unresolved signal', object:'cropped optical lens', rationale:'A lens narrows attention and enlarges the exact signal that still requires examination.', tension:'The unanswered detail hides inside an apparently complete conclusion.', emphasis:'CHƯA ĐƯỢC', support:[], improvement:'The optical object and the question share one focal action rather than sitting as separate components.', reuse:'Reusable for audits, source checks, research questions and claim verification.'},
  {copy:'MẢNH RỜI\n→\nMỘT HỆ THỐNG', semanticFunction:'transformation restructuring', semanticArchetype:'transformation' as const, semanticObject:'reassembly-field' as const, concept:'Fragments reorganise into one stable system', object:'material fragments resolving into an aligned plane', rationale:'Spatial reassembly makes structural transformation visible without explaining it as a diagram.', tension:'Useful parts remain weak until their relationships become ordered.', emphasis:'MỘT HỆ THỐNG', support:[], improvement:'Source fragments and resolved mass coexist in one cinematic field with perspective and material change.', reuse:'Reusable for cleaning, synthesis, workflow, learning and organisational change.'},
  {copy:'MỘT GIẢ ĐỊNH SAI\nKÉO LỆCH\nCẢ CHUỖI.', semanticFunction:'consequence payoff cascade', semanticArchetype:'consequence-payoff' as const, semanticObject:'domino-chain' as const, concept:'A small initiating error propagates through a system', object:'cropped material domino chain', rationale:'A domino cascade turns causal propagation into a recognisable consequence with off-frame continuation.', tension:'A local assumption can produce a system-wide deviation.', emphasis:'CẢ CHUỖI.', support:[], improvement:'Depth, scale recession and directional falloff carry consequence instead of an arrow diagram.', reuse:'Reusable for compounding errors, dependencies, risk and downstream impact.'},
  {copy:'NOISE: HEADER LẶP\nSIGNAL: GIÁ TRỊ = 42\nNOISE: FOOTER\nOUTPUT: GIÁ TRỊ = 42 · HỢP LỆ', semanticFunction:'evidence proof source artifact', semanticArchetype:'evidence-proof' as const, semanticObject:'document-field' as const, concept:'A traceable source reveals one trusted value after noise removal', object:'source document and overlapping resolved artifact', rationale:'The document field preserves provenance while the overlap exposes the exact trusted output.', tension:'Trust depends on separating retained signal from discarded noise.', emphasis:undefined, support:['GIÁ TRỊ = 42 · HỢP LỆ'], improvement:'Source, signal/noise, output and honesty label form a tactile hierarchy of trust—not a UI panel.', reuse:'Reusable for documents, datasets, transcripts, tests and captured evidence.'},
  {copy:'BỀ MẶT\nKHÔNG PHẢI\nCHIỀU SÂU.', semanticFunction:'reflection insight layers', semanticArchetype:'reflection-insight' as const, semanticObject:'layers' as const, concept:'Insight exists behind the first visible layer', object:'offset translucent material layers', rationale:'Layered planes embody the distance between a surface answer and the deeper structure beneath it.', tension:'The first available answer feels complete before deeper context appears.', emphasis:'CHIỀU SÂU.', support:[], improvement:'Atmospheric separation and occlusion make reflection spatial rather than merely quiet text.', reuse:'Reusable for nuance, hidden assumptions, second-order thinking and reframing.'},
  {copy:'TỰ TIN\nKHÔNG PHẢI\nBẰNG CHỨNG.', semanticFunction:'warning tension risk', semanticArchetype:'warning-tension' as const, semanticObject:'fracture' as const, concept:'Confidence fractures away from evidentiary authority', object:'split material plane with a pressure fracture', rationale:'A fracture creates the instability required to separate confidence from evidence without decorative geometry.', tension:'Tone can feel certain while the underlying basis remains absent.', emphasis:'KHÔNG PHẢI', support:[], improvement:'The diagonal break, compression and edge light create warning pressure with no warning icon or badge.', reuse:'Reusable for risk, contradiction, false certainty and boundary statements.'},
  {copy:'GIỮ LẠI\nĐIỀU\nCÓ CĂN CỨ.', semanticFunction:'conclusion distillation', semanticArchetype:'conclusion-distillation' as const, semanticObject:'aperture' as const, concept:'A narrow threshold leaves only the grounded conclusion', object:'off-centre light aperture', rationale:'The aperture acts as a threshold that filters noise and lets the distilled principle remain.', tension:'Distillation requires removing attractive but unsupported material.', emphasis:'CÓ CĂN CỨ.', support:[], improvement:'The conclusion lands through scale and a meaning-bearing threshold, not a decorative glow.', reuse:'Reusable for principles, closing reframes, decisions and calls to disciplined action.'},
];

export const GENERIC_GALLERY_REVIEW = Object.freeze(items.map(({semanticArchetype,improvement,reuse})=>({semanticArchetype,improvement,reuse})));

const directions = items.map((item)=>createSceneArtDirection({semanticFunction:item.semanticFunction,semanticArchetype:item.semanticArchetype,semanticObject:item.semanticObject,primaryFocus:item.copy,primaryVisualConcept:item.concept,primaryVisualObject:item.object,objectRationale:item.rationale,visualMetaphor:item.rationale,centralTension:item.tension,supportingElements:item.support,hierarchy:'One dominant idea; supporting material recedes.',emotionalTone:'premium editorial restraint',continuity:'Each gallery scene intentionally changes mode or anatomy.',strongAttractors:2,kineticRole:item.emphasis?'key-claim':undefined,emphasisText:item.emphasis,accentRationale:item.emphasis?'Amber isolates the semantic distinction, not a default line.':'none',proof:item.semanticArchetype==='evidence-proof'?{classification:'visual-representation',truthLabel:'BIỂU DIỄN TRUNG THỰC · KHÔNG PHẢI ẢNH CHỤP',provenance:'phase-1-generic-art-direction-gallery',evidenceAssetAvailable:true}:{classification:item.semanticArchetype==='investigation-verification'?'conceptual-metaphor':'none',truthLabel:item.semanticArchetype==='investigation-verification'?'ẨN DỤ ĐIỀU TRA TRỰC QUAN':'',provenance:item.semanticArchetype==='investigation-verification'?'phase-1-generic-art-direction-gallery':'',evidenceAssetAvailable:false}}));

export const GENERIC_ART_DIRECTION_GALLERY: AnimationManifest = {id:'CKAI-Generic-Art-Direction-Gallery',type:'short-form-animation',sourceVisualDirection:'phase-1-generic-art-direction-gallery',sourceVisualDirectionSha256:'0'.repeat(64),inputEligibility:'legacy-approved-reverse-audit',upstreamAnimationHandoffStatus:'BLOCKED',width:1080,height:1920,fps:30,totalSeconds:items.length,visualPresetId:DEFAULT_VISUAL_PRESET_ID,scenes:directions.map((artDirection,index)=>({id:`SC-0${index+1}` as `SC-0${number}`,startSeconds:index,endSeconds:index+1,purpose:itemPurpose(index),requiredAssetIds:[`A${index+1}`],requiredProofIds:[],requiredCaveatIds:[],motion:['reveal'],displayCopy:items[index].copy,artDirection})),assets:Object.fromEntries(items.map((item,index)=>[`A${index+1}`,{id:`A${index+1}`,kind:'text' as const,value:item.copy,source:'phase-1-generic-art-direction-gallery',truthLabel:directions[index].proof.truthLabel||'Synthetic cross-topic Visual Foundation proof'}])),proofIds:[],caveatIds:[],technicalQa:'BLOCKED',animationReview:'pending',humanDecision:'not-applicable',unresolvedBlockers:['creative gallery only; no production authority'],voiceHandoffStatus:'BLOCKED',voiceHandoff:{sourceScript:'none',implementationRef:'video-factory/animation/src/GenericArtDirectionGallery.tsx',technicalPreviewLocation:'generated/previews/visual-foundation-generic-gallery',totalDurationSeconds:items.length,hardMaximumSecondsExclusive:60,sceneSlots:items.map((item,index)=>({sceneId:`SC-0${index+1}` as `SC-0${number}`,startSeconds:index,endSeconds:index+1,spokenCopy:`Synthetic fixture narration for ${item.semanticArchetype}: ${item.copy.replace(/\n/g,' ')}`,pauseWindows:[]})),pronunciationSensitiveText:[],proofCaveatTiming:[],audioGenerated:false}};

function itemPurpose(index:number){return items[index].semanticArchetype;}
export const GenericArtDirectionGallery = ()=><AbsoluteFill>{GENERIC_ART_DIRECTION_GALLERY.scenes.map((scene,index)=><Sequence key={scene.id} from={index*30} durationInFrames={30}><VisualScene manifest={GENERIC_ART_DIRECTION_GALLERY} index={index}/></Sequence>)}</AbsoluteFill>;
