import assert from 'node:assert/strict';
import test from 'node:test';
import type {AnimationManifest} from '../../animation/src/model';
import type {PerceptualProgressionQa} from '../src/perceptual-qa';
import {FAILURE_RECOVERY_REGISTRY,applyRecoveryPlan,createCreativeReviewEscalation,createRecoveryPlan,diagnoseVisualFailures,executeAutomaticReplanLoop,recoveryRuleFor,type RecoveryRoundResult} from '../src/recovery';

const manifest=(id='CKAI-8123'):AnimationManifest=>({id:`${id}-Animation`,type:'short-form-animation',sourceVisualDirection:'direction.md',sourceVisualDirectionSha256:'A'.repeat(64),inputEligibility:'production',upstreamAnimationHandoffStatus:'READY',width:1080,height:1920,fps:30,totalSeconds:12,scenes:[
  {id:'SC-01',startSeconds:0,endSeconds:4,purpose:'Hook',requiredAssetIds:['A1'],requiredProofIds:[],requiredCaveatIds:[],motion:['reveal'],displayCopy:'QUESTION',hybridSource:{choice:'CODE_NATIVE',rationale:'logic'},artDirection:({objective:'key-insight',primaryFocus:'question',secondaryHierarchy:[],dominantElement:'question',visualMode:'typographic-editorial',primaryVisualConcept:'question broken by missing evidence',emotionalTone:'tension',narrationIntensity:'high',keyReveal:'gap',transitionOut:'CUT',safeAreaNotes:'safe',composition:'center',negativeSpaceRole:'gap',typographyHierarchy:'headline',contrastStrategy:'amber',lightingStrategy:'localized-glow',depthStrategy:'layers',focalPoint:'gap',motionPurpose:'reveal',animationBehavior:'transform',accentRationale:'gap',emphasisText:'QUESTION',primaryVisualObject:'editorial typography',supportingElements:['claim','gap','evidence'],centralTension:'certainty versus missing evidence',secondaryMotionRoles:[],semanticArchetype:'conclusion-distillation',retentionRole:'HOOK',visualModeRationale:'fixture',pattern:'fixture',archetype:'fixture',sourceStrategy:'code-native',semanticObject:'none',objectRationale:'none',transformationSequence:['a','b'],emotionalObjective:'alert',transitionLogic:'cut',forbiddenFallbackAnatomy:'generic card',proof:{classification:'none',truthLabel:'',provenance:'',evidenceAssetAvailable:false}}) as never,semanticMechanism:{version:1,scene_id:'SC-01',family:'hierarchy',viewer_question:'why',entities:['claim','gap','evidence'],relationships:['missing'],initial_state:'mixed',transformation:'labels appear',final_state:'labels remain',insight_revealed:'verify',typography_first:false,typography_exception_basis:null},retentionExecution:{version:1,scene_id:'SC-01',duration_target:4,beats:[0,1,2].map(i=>({beat_id:`SC-01-B0${i+1}`,start:i*4/3,end:(i+1)*4/3,purpose:i===0?'HOOK':'REVEAL',semantic_event:'event',visual_state:`state ${i}`,visual_state_change:'change',motion_purpose:'REVEAL',required_progression:'MEANING',perceptual_target:{minimum_change_level:2,dimensions:['SEMANTIC_MEANING'],dominant_state_key:`s${i}`}})),pause_budget:{max_unmotivated_pause:.6,justified_pauses:[]},exit_condition:'exit'}},
  {id:'SC-02',startSeconds:4,endSeconds:8,purpose:'Evidence',requiredAssetIds:['A2'],requiredProofIds:['P1'],requiredCaveatIds:[],motion:['compare'],displayCopy:'SOURCE',hybridSource:{choice:'REAL_EVIDENCE',rationale:'proof'},artDirection:undefined as never},
  {id:'SC-03',startSeconds:8,endSeconds:12,purpose:'Payoff',requiredAssetIds:['A3'],requiredProofIds:[],requiredCaveatIds:[],motion:['emphasis'],displayCopy:'VERIFY',hybridSource:{choice:'CODE_NATIVE',rationale:'payoff'},artDirection:undefined as never,semanticMechanism:{version:1,scene_id:'SC-03',family:'convergence',viewer_question:'then what',entities:['claim','evidence','decision'],relationships:['resolve'],initial_state:'apart',transformation:'labels appear',final_state:'slogan',insight_revealed:'verify',typography_first:true,typography_exception_basis:'payoff'}},
],assets:{A1:{id:'A1',kind:'text',value:'a',source:'approved',truthLabel:'approved'},A2:{id:'A2',kind:'text',value:'b',source:'proof',truthLabel:'actual'},A3:{id:'A3',kind:'text',value:'c',source:'approved',truthLabel:'approved'}},proofIds:['P1'],caveatIds:[],technicalQa:'PASS',animationReview:'pass',humanDecision:'approved',unresolvedBlockers:[],voiceHandoffStatus:'READY',voiceHandoff:{sourceScript:'approved.md',implementationRef:'generic',technicalPreviewLocation:'preview.mp4',totalDurationSeconds:12,hardMaximumSecondsExclusive:60,sceneSlots:[{sceneId:'SC-01',startSeconds:0,endSeconds:4,spokenCopy:'a',pauseWindows:[]},{sceneId:'SC-02',startSeconds:4,endSeconds:8,spokenCopy:'b',pauseWindows:[]},{sceneId:'SC-03',startSeconds:8,endSeconds:12,spokenCopy:'c',pauseWindows:[]}],pronunciationSensitiveText:[],proofCaveatTiming:[],audioGenerated:false}});

const qa=(failure='HOOK_VISUALLY_STATIC',scene='SC-01')=>({scenes:[{scene_id:scene,failure_classes:[failure],beats:[{failure_reasons:['static centered typography']}]}],failure_classes:[failure]}) as unknown as PerceptualProgressionQa;

test('central registry routes deterministic, creative, source and runtime failures',()=>{assert.equal(recoveryRuleFor('POST_INFORMATION_LINGER').recovery_mode,'DETERMINISTIC_FIX');assert.equal(recoveryRuleFor('HOOK_VISUALLY_STATIC').recovery_mode,'CREATIVE_REPLAN');assert.equal(recoveryRuleFor('SEMANTIC_ASSET_MISMATCH').recovery_mode,'SOURCE_REPLAN');assert.equal(recoveryRuleFor('RETENTION_PLAN_EXECUTION_MISMATCH').recovery_mode,'RUNTIME_FIX');assert.ok(Object.keys(FAILURE_RECOVERY_REGISTRY).length>=15);});

test('diagnosis creates scene-local recovery with do-not-repeat memory',()=>{const source=manifest();const diagnosis=diagnoseVisualFailures(qa());const plan=createRecoveryPlan(source,diagnosis,1);assert.equal(plan.actions[0]?.scene_id,'SC-01');assert.equal(plan.actions[0]?.variant,'HOOK_EXPECTATION_BREAK');assert.ok(plan.actions[0]?.do_not_repeat.includes('same hook plus more animation'));const changed=applyRecoveryPlan(source,plan);assert.equal(changed.scenes[0]?.visualRecovery?.round,1);assert.notEqual(changed.scenes[0]?.semanticMechanism?.family,source.scenes[0]?.semanticMechanism?.family);assert.equal(source.scenes[0]?.visualRecovery,undefined);});

test('retention copy of a scene failure does not become a whole-video overwrite',()=>{const diagnosis=diagnoseVisualFailures(qa('HOOK_VISUALLY_STATIC'),['HOOK_VISUALLY_STATIC'],[]);assert.equal(diagnosis.length,1);assert.equal(diagnosis[0]?.scene_id,'SC-01');assert.equal(createRecoveryPlan(manifest(),diagnosis,1).actions.length,1);});

test('aggregate retention mismatch does not mask concrete perceptual recovery',()=>{const diagnosis=diagnoseVisualFailures(qa('HOOK_VISUALLY_STATIC'),['RETENTION_PLAN_EXECUTION_MISMATCH','HOOK_VISUALLY_STATIC'],[]);assert.equal(diagnosis.length,1);assert.equal(diagnosis[0]?.failure_class,'HOOK_VISUALLY_STATIC');assert.equal(createRecoveryPlan(manifest(),diagnosis,1).actions[0]?.recovery_mode,'CREATIVE_REPLAN');});

test('deterministic timing fix does not consume creative decoration',()=>{const source=manifest();const plan=createRecoveryPlan(source,diagnoseVisualFailures(qa('POST_INFORMATION_LINGER','SC-01')),1);assert.equal(plan.actions[0]?.recovery_mode,'DETERMINISTIC_FIX');assert.equal(plan.actions[0]?.variant,'OBJECT_PROCESS');assert.ok((applyRecoveryPlan(source,plan).totalSeconds)<source.totalSeconds);});

test('Round 2 differs meaningfully from Round 1 and remembers prior attempt',()=>{const source=manifest();const diagnosis=diagnoseVisualFailures(qa('SEMANTIC_MECHANISM_VISUALLY_UNDERPOWERED'));const one=createRecoveryPlan(source,diagnosis,1);const m1=applyRecoveryPlan(source,one);const history=[{round:1,scene_id:'SC-01',source:'CODE_NATIVE',concept:'object filtering transformation',mechanism:m1.scenes[0]!.semanticMechanism!.family,visual_states:['object filtering transformation'],failures:['SEMANTIC_MECHANISM_VISUALLY_UNDERPOWERED'],qa_evidence:['still weak']}];const two=createRecoveryPlan(m1,diagnosis,2,history);assert.notEqual(two.actions[0]?.mechanism_after,one.actions[0]?.mechanism_after);assert.ok(two.contexts[0]?.do_not_repeat.includes('object filtering transformation'));});

test('evidence can never source-escalate into generated proof',()=>{const source=manifest();const diagnosis=diagnoseVisualFailures(qa('SEMANTIC_ASSET_MISMATCH','SC-02'));const plan=createRecoveryPlan(source,diagnosis,2);assert.equal(plan.actions[0]?.source_before,'REAL_EVIDENCE');assert.equal(plan.actions[0]?.source_after,'REAL_EVIDENCE');assert.equal(plan.image_generation_attempts,0);});

test('whole-video failures create one whole-video replan while scene failures remain selective',()=>{const source=manifest();const local=createRecoveryPlan(source,diagnoseVisualFailures(qa()),1);assert.equal(local.whole_video,false);assert.equal(local.actions.length,1);const whole=createRecoveryPlan(source,diagnoseVisualFailures({scenes:[],failure_classes:[]} as unknown as PerceptualProgressionQa,[],['VISUAL_PATTERN_FATIGUE']),1);assert.equal(whole.whole_video,true);assert.equal(whole.actions[0]?.scene_id,null);});

test('automatic loop stops immediately on PASS and never exceeds two rounds',async()=>{const source=manifest();const passing:RecoveryRoundResult={manifest:source,diagnoses:[],machine_pass:true,qa:{},attempts:[]};let calls=0;const pass=await executeAutomaticReplanLoop({initial:passing,runRound:async()=>{calls++;return passing;}});assert.equal(pass.rounds_used,0);assert.equal(calls,0);const failing:RecoveryRoundResult={manifest:source,diagnoses:diagnoseVisualFailures(qa()),machine_pass:false,qa:{},attempts:[]};const exhausted=await executeAutomaticReplanLoop({initial:failing,runRound:async(manifest)=>{calls++;return {...failing,manifest};}});assert.equal(exhausted.status,'NEEDS_CHATGPT_CREATIVE_REVIEW');assert.equal(exhausted.rounds_used,2);assert.equal(calls,2);const escalation=createCreativeReviewEscalation('CKAI-8123',exhausted);assert.equal(escalation.status,'NEEDS_CHATGPT_CREATIVE_REVIEW');assert.ok(escalation.failed_scenes[0]?.do_not_repeat.length);});

test('scene escalation summary includes a whole-video recovery round',async()=>{const source=manifest();const failing:RecoveryRoundResult={manifest:source,diagnoses:diagnoseVisualFailures(qa()),machine_pass:false,qa:{},attempts:[]};const result=await executeAutomaticReplanLoop({initial:failing,max_rounds:1,runRound:async(manifest)=>({...failing,manifest})});result.rounds.push({plan:{version:1,round:2,whole_video:true,image_generation_attempts:0,contexts:[],actions:[{scene_id:null,failures:['VISUAL_PATTERN_FATIGUE'],priority:'P1',recovery_mode:'CREATIVE_REPLAN',return_layer:'Whole-video Visual Director',variant:'WHOLE_VIDEO_RESET',source_before:'WHOLE_VIDEO',source_after:'WHOLE_VIDEO',do_not_repeat:['repeated card cadence'],required_improvement:['vary mode sequence']}]},result:failing});const escalation=createCreativeReviewEscalation('CKAI-8123',result);assert.equal(escalation.failed_scenes[0]?.attempts_summary.at(-1)?.concept,'WHOLE_VIDEO_RESET');});

test('runtime failure skips creative rounds and arbitrary IDs have no special branch',async()=>{const source=manifest('CKAI-9998');const initial:RecoveryRoundResult={manifest:source,diagnoses:diagnoseVisualFailures(qa('RETENTION_PLAN_EXECUTION_MISMATCH')),machine_pass:false,qa:{},attempts:[]};let called=false;const result=await executeAutomaticReplanLoop({initial,runRound:async()=>{called=true;return initial;}});assert.equal(called,false);assert.equal(result.status,'NEEDS_CHATGPT_CREATIVE_REVIEW');const implementation=`${createRecoveryPlan}${applyRecoveryPlan}${executeAutomaticReplanLoop}`;assert.doesNotMatch(implementation,/CKAI-0004|contentId\s*===/);});
