import type {AnimationManifest,Scene} from '../../animation/src/model';
import type {EmbodimentDecision,EmbodimentLevel,EmbodimentMaterial,EmbodimentPlan,IdentityChannel,SemanticSignature} from '../../animation/src/embodiment';
import type {ProcessObject,ProcessPlan,SemanticObjectType} from '../../animation/src/representation';

export const IDENTITY_FAILURE_CLASSES=['SEMANTIC_OBJECT_IDENTITY_NOT_PERCEPTIBLE','GENERIC_ABSTRACT_NODE_SUBSTITUTION','SEMANTIC_ROLE_VISUALLY_AMBIGUOUS','HYPOTHESIS_IDENTITY_NOT_PERCEPTIBLE','EVIDENCE_IDENTITY_NOT_PERCEPTIBLE','FACT_INFERENCE_DISTINCTION_NOT_PERCEPTIBLE','UNKNOWN_NOT_VISUALLY_UNRESOLVED','OBJECT_ACTS_BEFORE_IDENTITY_ESTABLISHED','OBJECT_IDENTITY_LOST_DURING_MOTION','OBJECT_IDENTITY_LOST_DURING_TRANSFORMATION','LABEL_DEFINES_OBJECT_IDENTITY','EDITORIAL_OVERLAY_COMPENSATING_FOR_VISUAL','PRODUCTION_LANGUAGE_INCONSISTENCY','ABSTRACTION_LEVEL_TOO_HIGH','EMBODIMENT_CAPABILITY_MISSING','GENERIC_EMBODIMENT_PATTERN_REUSE'] as const;
export type IdentityFailureClass=typeof IDENTITY_FAILURE_CLASSES[number];
export type IdentityFailureOrigin='EMBODIMENT_PLAN'|'EMBODIMENT_CAPABILITY'|'IDENTITY_REALIZATION'|'MOTION_SPATIAL_REALIZATION'|'TIMING'|'REPRESENTATION_PLAN'|'SOURCE'|'QA_MISMATCH'|'WHOLE_VIDEO_EMBODIMENT';

type SelectionContext={scene:Scene;plan:ProcessPlan;object:ProcessObject;recent_materials:EmbodimentMaterial[];repairPass:0|1;repairFailures:string[]};
const sourceLevel=(plan:ProcessPlan):EmbodimentLevel=>plan.source_type==='REAL_EVIDENCE'?'LEVEL_1_REAL_SOURCE':'LEVEL_3_SEMANTIC_DIAGRAMMATIC';
const roleMaterial=(role:SemanticObjectType,plan:ProcessPlan):{level:EmbodimentLevel;material:EmbodimentMaterial;channels:IdentityChannel[]}=>{
  if(role==='EVIDENCE'||role==='SOURCE_REGION')return {level:plan.source_type==='REAL_EVIDENCE'?'LEVEL_1_REAL_SOURCE':'LEVEL_2_RECOGNIZABLE_MATERIAL',material:'SOURCE_FRAGMENT',channels:['SOURCE_PROVENANCE','MORPHOLOGY','RELATIONSHIP','LINEAGE']};
  if(role==='CLAIM')return {level:'LEVEL_2_RECOGNIZABLE_MATERIAL',material:'PROPOSITION_FRAGMENT',channels:['MORPHOLOGY','RELATIONSHIP','LIFECYCLE']};
  if(role==='FACT')return {level:sourceLevel(plan),material:'STABLE_ANCHOR',channels:['STABILITY','RELATIONSHIP','LINEAGE']};
  if(role==='INFERENCE')return {level:'LEVEL_3_SEMANTIC_DIAGRAMMATIC',material:'DERIVED_TRAIL',channels:['LINEAGE','RELATIONSHIP','STABILITY']};
  if(role==='HYPOTHESIS')return {level:'LEVEL_3_SEMANTIC_DIAGRAMMATIC',material:'BRANCH_CANDIDATE',channels:['SPATIAL_ROLE','RELATIONSHIP','LIFECYCLE']};
  if(role==='UNKNOWN')return {level:'LEVEL_3_SEMANTIC_DIAGRAMMATIC',material:'NEGATIVE_SPACE_GAP',channels:['MORPHOLOGY','RELATIONSHIP','SPATIAL_ROLE']};
  if(role==='OUTCOME')return {level:'LEVEL_2_RECOGNIZABLE_MATERIAL',material:'OUTCOME_MARKER',channels:['MORPHOLOGY','SPATIAL_ROLE','STABILITY']};
  if(role==='VARIABLE'||role==='CAUSE')return {level:'LEVEL_2_RECOGNIZABLE_MATERIAL',material:'VARIABLE_CONTROL',channels:['BEHAVIOR','RELATIONSHIP','LIFECYCLE']};
  if(role==='CONFIDENCE_STATE')return {level:'LEVEL_3_SEMANTIC_DIAGRAMMATIC',material:'STABILITY_FIELD',channels:['STABILITY','BEHAVIOR','RELATIONSHIP']};
  if(role==='VERIFICATION_GATE')return {level:'LEVEL_3_SEMANTIC_DIAGRAMMATIC',material:'INTERACTIVE_GATE',channels:['BEHAVIOR','SPATIAL_ROLE','LIFECYCLE']};
  if(role==='CONCLUSION')return {level:'LEVEL_3_SEMANTIC_DIAGRAMMATIC',material:'EARNED_CONCLUSION',channels:['LIFECYCLE','RELATIONSHIP','STABILITY']};
  if(role==='PRINCIPLE')return {level:'LEVEL_2_RECOGNIZABLE_MATERIAL',material:'TERMINAL_PRINCIPLE',channels:['LIFECYCLE','STABILITY','MORPHOLOGY']};
  return {level:'LEVEL_4_ABSTRACT_NODE',material:'ABSTRACT_NODE',channels:['RELATIONSHIP','SPATIAL_ROLE']};
};
const stability=(role:SemanticObjectType):SemanticSignature['stability']=>role==='FACT'||role==='EVIDENCE'||role==='SOURCE_REGION'||role==='OUTCOME'?'GROUNDED':role==='UNKNOWN'?'UNRESOLVED':role==='VARIABLE'||role==='CAUSE'?'VARIABLE':role==='CONCLUSION'||role==='PRINCIPLE'?'EARNED':'PROVISIONAL';
const morphology=(material:EmbodimentMaterial)=>({SOURCE_FRAGMENT:'cropped source fragment with provenance rail',PROPOSITION_FRAGMENT:'open proposition strip with unfinished edge',STABLE_ANCHOR:'grounded baseline and source tether',DERIVED_TRAIL:'derived extension from an upstream anchor',BRANCH_CANDIDATE:'candidate attached to an independent branch path',NEGATIVE_SPACE_GAP:'missing interval/incomplete bridge',OUTCOME_MARKER:'observed-state strip with baseline delta',VARIABLE_CONTROL:'relational control/mediating component',STABILITY_FIELD:'supported and unsupported zones with distinct solidity',INTERACTIVE_GATE:'criterion aperture with pass/fail destinations',EARNED_CONCLUSION:'initially absent terminal receiving verified paths',TERMINAL_PRINCIPLE:'stable terminal editorial structure earned by prior events',ABSTRACT_NODE:'minimal geometry whose relationship context must carry identity'}[material]);

export const selectEmbodiment=(context:SelectionContext):EmbodimentDecision=>{const selected=roleMaterial(context.object.type,context.plan);const repeated=context.recent_materials.filter(item=>item===selected.material).length;const repaired=context.repairPass===1;const level=repaired&&selected.level==='LEVEL_4_ABSTRACT_NODE'?'LEVEL_3_SEMANTIC_DIAGRAMMATIC':selected.level;const material=repaired&&selected.material==='ABSTRACT_NODE'?'PROPOSITION_FRAGMENT':selected.material;const channels=[...selected.channels];if(repaired&&!channels.includes('MORPHOLOGY'))channels.push('MORPHOLOGY');if(repaired&&!channels.includes('RELATIONSHIP'))channels.push('RELATIONSHIP');return {semantic_role:context.object.type,selected_level:level,selected_material:material,identity_channels:channels,selection_reason:`${context.object.type} in ${context.plan.retention_role}/${context.plan.source_type} needs ${channels.join('+')} identity; selected ${material} rather than a universal node.${repaired?' Identity diagnosis reinforces role morphology, establishment, relationship attachment and lineage at render time.':''}`,rejected_alternatives:[{level:'LEVEL_4_ABSTRACT_NODE',material:'ABSTRACT_NODE',reason:'Rejected when role identity would depend mainly on color or label.'},{level:'LEVEL_2_RECOGNIZABLE_MATERIAL',material:'VARIABLE_CONTROL',reason:'Rejected when its behavior/source affordance does not match this semantic role.'}],capability_match:'PASS',abstraction_risk:level==='LEVEL_4_ABSTRACT_NODE'?'HIGH':repeated>=2?'MEDIUM':'LOW',scene_role:context.plan.retention_role,source_type:context.plan.source_type,realization_profile:{morphology_variant:repaired?'ROLE_REINFORCED':'BASE',establishment_emphasis:repaired?'REINFORCED':'STANDARD',relationship_attachment:repaired?'EXPLICIT':'STANDARD',lineage_visibility:repaired?'REINFORCED':'STANDARD',label_dependency:repaired?'REDUCED':'STANDARD',repair_claims_viewer_facing_change:repaired,repair_reason:repaired?context.repairFailures.join('|')||'IDENTITY_REALIZATION':null}};};
const signatureFor=(object:ProcessObject,decision:EmbodimentDecision,plan:ProcessPlan):SemanticSignature=>{const repaired=decision.realization_profile.repair_claims_viewer_facing_change;return {semantic_role:object.type,embodiment_level:decision.selected_level,morphology:`${morphology(decision.selected_material)}${repaired?' with role-specific identity reinforcement':''}`,spatial_role:`${object.type==='UNKNOWN'?'occupies unresolved interval':object.type==='HYPOTHESIS'?'owns a candidate branch':object.type==='EVIDENCE'||object.type==='SOURCE_REGION'?'enters from source space':object.type==='FACT'?'anchors derived reasoning':'inherits topology-assigned semantic territory'}${repaired?'; attachment remains explicit while acting':''}`,motion_behavior:object.type==='FACT'?'settles with low motion noise':object.type==='HYPOTHESIS'?'branches, competes and can leave active field':object.type==='UNKNOWN'?'persists as incomplete space':object.type==='EVIDENCE'?'enters from source and anchors support':'acts only after establishment',relationship_behavior:`${object.type==='CAUSE'?'requires supported directional mechanism':object.type==='INFERENCE'?'extends from grounded inputs':object.type==='CLAIM'?'receives support or remains provisional':'uses typed ProcessPlan relationships'}${repaired?'; renderer exposes the attachment rather than relying on the label':''}`,lifecycle:['ESTABLISH','ACT','REACT','TRANSFORM','SETTLE',...(object.type==='HYPOTHESIS'?['EXIT' as const]:['RESOLVE' as const])],stability:stability(object.type),source_affordance:`${plan.source_type==='REAL_EVIDENCE'?'preserve source region, provenance and fragment character':object.type==='EVIDENCE'||object.type==='FACT'?'retain derived lineage to source':'no evidence authority implied'}${repaired?'; lineage rail is viewer-facing':''}`,lineage:{derived_from:object.type==='FACT'||object.type==='INFERENCE'?['source']:[],transformed_from:null,preserves_identity:true},text_dependency:repaired?'NONE':'LOW',identity_channels:decision.identity_channels,transition_kind:object.type==='INFERENCE'?'DERIVED_OBJECT_CREATION':'SAME_OBJECT_STATE_CHANGE'};};

export const compileEmbodimentPlan=(scene:Scene,recentMaterials:EmbodimentMaterial[]=[],repairPass:0|1=0,repairFailures:string[]=[]):EmbodimentPlan=>{const plan=scene.representationPlan;if(!plan)return {version:1,scene_id:scene.id,decisions:{},signatures:{},establish_before_act:false,abstract_node_budget:{anonymous_count:0,distinct_roles_using_abstract_node:0,verdict:'FAIL'},compile_failures:['EMBODIMENT_CAPABILITY_MISSING'],repair:{pass:repairPass,diagnosis:[]}};const decisions:Record<string,EmbodimentDecision>={},signatures:Record<string,SemanticSignature>={};for(const object of plan.objects){const decision=selectEmbodiment({scene,plan,object,recent_materials:recentMaterials,repairPass,repairFailures});const signature=signatureFor(object,decision,plan);decisions[object.id]=decision;signatures[object.id]=signature;object.embodiment_decision=decision;object.semantic_signature=signature;recentMaterials.push(decision.selected_material);}const abstracts=Object.entries(decisions).filter(([,decision])=>decision.selected_level==='LEVEL_4_ABSTRACT_NODE');const roles=new Set(abstracts.map(([,decision])=>decision.semantic_role));const compile_failures:string[]=[];if(Object.values(decisions).some(item=>item.identity_channels.filter(channel=>channel!=='TEXT_CONFIRMATION').length<2))compile_failures.push('SEMANTIC_ROLE_VISUALLY_AMBIGUOUS');if(abstracts.length>1&&roles.size>1)compile_failures.push('GENERIC_ABSTRACT_NODE_SUBSTITUTION');if(Object.values(decisions).some(item=>item.capability_match==='FAIL'))compile_failures.push('EMBODIMENT_CAPABILITY_MISSING');const firstComplex=plan.events.find(event=>['BRANCH','FILTER','VERIFY','MERGE','CONVERGE','TRANSFORM'].includes(event.type));const establish=plan.events.find(event=>event.type==='INTRODUCE'||event.type==='REGION_REVEAL');const establishBeforeAct=Boolean(establish&&(!firstComplex||establish.at<firstComplex.at));if(!establishBeforeAct)compile_failures.push('OBJECT_ACTS_BEFORE_IDENTITY_ESTABLISHED');return {version:1,scene_id:scene.id,decisions,signatures,establish_before_act:establishBeforeAct,abstract_node_budget:{anonymous_count:abstracts.length,distinct_roles_using_abstract_node:roles.size,verdict:abstracts.length>1&&roles.size>1?'FAIL':'PASS'},compile_failures,repair:{pass:repairPass,diagnosis:repairPass?[`Viewer-facing identity realization strengthened for: ${repairFailures.join(', ')||'identity realization diagnosis'}.`]:[]}};};
export const compileEmbodimentPlans=(manifest:AnimationManifest,repairPass:0|1=0)=>{const recent:EmbodimentMaterial[]=[];for(const scene of manifest.scenes){if(!scene.representationPlan)continue;scene.representationPlan.embodiment=compileEmbodimentPlan(scene,recent,repairPass);scene.representationPlan.compile_failures=[...new Set([...scene.representationPlan.compile_failures,...scene.representationPlan.embodiment.compile_failures])];}return manifest;};
export const diagnoseIdentityFailureOrigin=(failure:string):IdentityFailureOrigin=>failure==='EMBODIMENT_CAPABILITY_MISSING'?'EMBODIMENT_CAPABILITY':failure==='ABSTRACTION_LEVEL_TOO_HIGH'||failure==='GENERIC_ABSTRACT_NODE_SUBSTITUTION'?'EMBODIMENT_PLAN':failure==='OBJECT_ACTS_BEFORE_IDENTITY_ESTABLISHED'?'TIMING':failure==='OBJECT_IDENTITY_LOST_DURING_MOTION'?'MOTION_SPATIAL_REALIZATION':failure==='PRODUCTION_LANGUAGE_INCONSISTENCY'?'SOURCE':failure==='GENERIC_EMBODIMENT_PATTERN_REUSE'?'WHOLE_VIDEO_EMBODIMENT':failure.includes('IDENTITY')||failure.includes('LABEL_')||failure.includes('EDITORIAL_OVERLAY')?'IDENTITY_REALIZATION':'QA_MISMATCH';
export const repairIdentity=(manifest:AnimationManifest,diagnoses:Array<{scene_id:string;failure_class:string}>)=>{const output=structuredClone(manifest);const eligible=diagnoses.filter(item=>['EMBODIMENT_PLAN','IDENTITY_REALIZATION','TIMING'].includes(diagnoseIdentityFailureOrigin(item.failure_class)));const byScene=new Map<string,string[]>();for(const item of eligible)byScene.set(item.scene_id,[...new Set([...(byScene.get(item.scene_id)??[]),item.failure_class])]);for(const scene of output.scenes){const current=scene.representationPlan?.embodiment,failures=byScene.get(scene.id);if(!current||!failures?.length)continue;if(current.repair.pass>=1)throw new Error('IDENTITY_REPAIR_LIMIT_EXCEEDED');scene.representationPlan!.embodiment=compileEmbodimentPlan(scene,[],1,failures);for(const object of scene.representationPlan!.objects){const decision=scene.representationPlan!.embodiment!.decisions[object.id]!;object.embodiment_decision=decision;object.semantic_signature=scene.representationPlan!.embodiment!.signatures[object.id];}}return output;};
