import {createHash} from 'node:crypto';
import {mkdirSync,readFileSync} from 'node:fs';
import {basename,join} from 'node:path';
import {spawnSync} from 'node:child_process';
import type {AnimationManifest} from '../../animation/src/model';
import {resolveFfmpeg} from '../../shared/media-tools';
import type {OpenAiLike} from './openai-service';

export const PERCEPTUAL_FAILURE_CLASSES=['BEAT_EXECUTED_BUT_NOT_PERCEPTUALLY_DISTINCT','PERCEPTUAL_HOLD_TOO_LONG','HOOK_VISUALLY_STATIC','LONG_SCENE_NO_REENGAGEMENT','POST_INFORMATION_LINGER','SEMANTIC_MECHANISM_VISUALLY_UNDERPOWERED','MICROCOPY_OVERLOAD','PAYOFF_AS_END_CARD'] as const;
export type PerceptualFailureClass=typeof PERCEPTUAL_FAILURE_CLASSES[number];
export type ChangeLevel=1|2|3;
export type PerceptualBeatQa={beat_id:string;visual_delta:number;semantic_delta:number;attention_delta:number;expectation_delta:number;change_level:ChangeLevel;perceptually_distinct:boolean;dominant_state:string;reading_burden:number;failure_reasons:string[]};
export type MotionSpatialVisionObservation={topology_change:number;spatial_change:number;relationship_change:number;focal_change:number;object_state_change:number;semantic_readability:number;centered_composition:boolean;cardless_card:boolean;generic_motion_anatomy:boolean;source_viewport_traversed:boolean;source_orientation_preserved:boolean;limitation_directed:boolean;payoff_complexity_reduced:boolean;diagnostic_overlay_text:string[];motion_summary:string};
export type ObjectIdentityVisionObservation={objects:Array<{object_id:string;planned_role:string;visible_material:string;role_readability:number;identity_channels_visible:string[];label_dependency:number;identity_before_motion:boolean;identity_after_motion:boolean;relationship_clarity:number;transformation_continuity:number}>;distinct_roles_without_labels:boolean;evidence_source_authority:boolean;unknown_visually_unresolved:boolean;fact_inference_distinct:boolean;editorial_overlay_compensates:boolean;production_language_consistent:boolean;authored_english_overlay:string[];generic_abstract_node_substitution:boolean;generic_embodiment_reuse:boolean;identity_summary:string};
export type PerceptualSceneVisionQa={scene_id:string;summary:string;beats:PerceptualBeatQa[];hook_strong_event:boolean;long_scene_reengagement:boolean;evidence_payload_complete_at_beat:string|null;post_information_linger:boolean;mechanism_visually_underpowered:boolean;microcopy_overload:boolean;payoff_visual_impact:number;payoff_as_end_card:boolean;motion_spatial?:MotionSpatialVisionObservation;object_identity?:ObjectIdentityVisionObservation};
export type PerceptualSceneQa=PerceptualSceneVisionQa&{planned_beats:number;executed_beats:number;perceptually_distinct_beats:number;weak_beats:number;perceived_beat_ratio:number;long_same_state_seconds:number;verdict:'PASS'|'FAIL';failure_classes:PerceptualFailureClass[]};
export type PerceptualProgressionQa={version:1;actual_binary:true;model:string;video_path:string;video_sha256:string;contract_sha256:string;sampling_strategy:'ONE_ORDERED_STATE_PER_BEAT_MAX_FOUR_PER_SCENE';vision_calls:number;sampled_images:number;scenes:PerceptualSceneQa[];strongest_beats:string[];weak_beats:string[];long_same_state_windows:Array<{scene_id:string;seconds:number}>;hook_distinct_events:number;mid_video_reengagement:boolean;payoff_visual_impact:number;verdict:'PASS'|'FAIL';failure_classes:PerceptualFailureClass[];usage:Array<Record<string,unknown>>};
export type PerceptualSample={scene_id:string;beat_id:string;time_seconds:number;path:string;sha256:string};

const sha=(value:Buffer)=>createHash('sha256').update(value).digest('hex').toUpperCase();
const round=(value:number)=>Number(value.toFixed(3));
const clampScore=(value:number)=>Math.max(0,Math.min(10,Math.round(value)));

export const isPerceptuallyDistinct=(beat:Pick<PerceptualBeatQa,'visual_delta'|'semantic_delta'|'attention_delta'|'expectation_delta'|'change_level'>)=>beat.change_level>=2&&Math.max(beat.visual_delta,beat.semantic_delta,beat.attention_delta,beat.expectation_delta)>=6;

export const normalizePerceptualSceneQa=(manifest:AnimationManifest,raw:PerceptualSceneVisionQa):PerceptualSceneQa=>{
  const scene=manifest.scenes.find((item)=>item.id===raw.scene_id);if(!scene)throw new Error(`Unknown perceptual scene ${raw.scene_id}`);
  const contract=scene.retentionExecution;const planned=contract?.beats.length??0;const duration=scene.endSeconds-scene.startSeconds;
  const beats=(contract?.beats??[]).map((plannedBeat,index)=>{const source=raw.beats.find((item)=>item.beat_id===plannedBeat.beat_id)??raw.beats[index]??{beat_id:plannedBeat.beat_id,visual_delta:0,semantic_delta:0,attention_delta:0,expectation_delta:0,change_level:1 as const,perceptually_distinct:false,dominant_state:'unassessed',reading_burden:10,failure_reasons:['Vision omitted the planned beat']};const normalized={...source,beat_id:plannedBeat.beat_id,visual_delta:clampScore(source.visual_delta),semantic_delta:clampScore(source.semantic_delta),attention_delta:clampScore(source.attention_delta),expectation_delta:clampScore(source.expectation_delta),reading_burden:clampScore(source.reading_burden),change_level:Math.max(1,Math.min(3,Math.round(source.change_level))) as ChangeLevel};return {...normalized,perceptually_distinct:isPerceptuallyDistinct(normalized)};});
  const distinct=beats.filter((beat)=>beat.perceptually_distinct).length;const weak=beats.length-distinct;let longest=0,current=0;for(let index=0;index<beats.length;index++){const span=contract?contract.beats[index]!.end-contract.beats[index]!.start:duration/beats.length;if(beats[index]!.perceptually_distinct)current=0;else{current+=span;longest=Math.max(longest,current);}}
  const failures:PerceptualFailureClass[]=[];if(weak)failures.push('BEAT_EXECUTED_BUT_NOT_PERCEPTUALLY_DISTINCT');if(longest>5)failures.push('PERCEPTUAL_HOLD_TOO_LONG');if(scene.id===manifest.scenes[0]?.id&&!raw.hook_strong_event)failures.push('HOOK_VISUALLY_STATIC');if(duration>=6&&!raw.long_scene_reengagement)failures.push('LONG_SCENE_NO_REENGAGEMENT');if(raw.post_information_linger)failures.push('POST_INFORMATION_LINGER');if(scene.hybridSource?.choice==='CODE_NATIVE'&&raw.mechanism_visually_underpowered)failures.push('SEMANTIC_MECHANISM_VISUALLY_UNDERPOWERED');if(raw.microcopy_overload)failures.push('MICROCOPY_OVERLOAD');if(scene.id===manifest.scenes.at(-1)?.id&&(raw.payoff_as_end_card||raw.payoff_visual_impact<7))failures.push('PAYOFF_AS_END_CARD');
  const ratio=planned?distinct/planned:0;const cleanRatio=scene.id===manifest.scenes[0]?.id||scene.id===manifest.scenes.at(-1)?.id?ratio>=.67:ratio>=.5;const hard=failures.some((failure)=>failure!=='BEAT_EXECUTED_BUT_NOT_PERCEPTUALLY_DISTINCT')||!cleanRatio;
  return {...raw,beats,planned_beats:planned,executed_beats:planned,perceptually_distinct_beats:distinct,weak_beats:weak,perceived_beat_ratio:round(ratio),long_same_state_seconds:round(longest),verdict:hard?'FAIL':'PASS',failure_classes:[...new Set(failures)]};
};

export const selectPerceptualSamples=(manifest:AnimationManifest):Array<{scene_id:string;beat_id:string;time_seconds:number}>=>manifest.scenes.flatMap((scene)=>{
  const beats=scene.retentionExecution?.beats??[];const chosen=beats.length<=4?beats:[beats[0]!,beats[Math.floor((beats.length-1)/2)]!,beats.at(-2)!,beats.at(-1)!];
  return chosen.map((beat)=>({scene_id:scene.id,beat_id:beat.beat_id,time_seconds:round(scene.startSeconds+(beat.start+beat.end)/2)}));
});

export const extractPerceptualSamples=(videoPath:string,manifest:AnimationManifest,outputDir:string):PerceptualSample[]=>{
  mkdirSync(outputDir,{recursive:true});return selectPerceptualSamples(manifest).map((sample,index)=>{const path=join(outputDir,`${String(index+1).padStart(2,'0')}-${sample.scene_id}-${sample.beat_id}.jpg`);const result=spawnSync(resolveFfmpeg(),['-hide_banner','-loglevel','error','-y','-ss',String(sample.time_seconds),'-i',videoPath,'-frames:v','1','-q:v','3',path],{encoding:'utf8',timeout:60_000});if(result.status!==0)throw new Error(`Perceptual sample extraction failed: ${result.stderr}`);const binary=readFileSync(path);return {...sample,path,sha256:sha(binary)};});
};

const objectIdentitySchema={type:'object',additionalProperties:false,properties:{objects:{type:'array',items:{type:'object',additionalProperties:false,properties:{object_id:{type:'string'},planned_role:{type:'string'},visible_material:{type:'string'},role_readability:{type:'integer',minimum:0,maximum:10},identity_channels_visible:{type:'array',items:{type:'string'}},label_dependency:{type:'integer',minimum:0,maximum:10},identity_before_motion:{type:'boolean'},identity_after_motion:{type:'boolean'},relationship_clarity:{type:'integer',minimum:0,maximum:10},transformation_continuity:{type:'integer',minimum:0,maximum:10}},required:['object_id','planned_role','visible_material','role_readability','identity_channels_visible','label_dependency','identity_before_motion','identity_after_motion','relationship_clarity','transformation_continuity']}},distinct_roles_without_labels:{type:'boolean'},evidence_source_authority:{type:'boolean'},unknown_visually_unresolved:{type:'boolean'},fact_inference_distinct:{type:'boolean'},editorial_overlay_compensates:{type:'boolean'},production_language_consistent:{type:'boolean'},authored_english_overlay:{type:'array',items:{type:'string'}},generic_abstract_node_substitution:{type:'boolean'},generic_embodiment_reuse:{type:'boolean'},identity_summary:{type:'string'}},required:['objects','distinct_roles_without_labels','evidence_source_authority','unknown_visually_unresolved','fact_inference_distinct','editorial_overlay_compensates','production_language_consistent','authored_english_overlay','generic_abstract_node_substitution','generic_embodiment_reuse','identity_summary']} as const;
const sceneSchema={type:'object',additionalProperties:false,properties:{scene_id:{type:'string'},summary:{type:'string'},beats:{type:'array',items:{type:'object',additionalProperties:false,properties:{beat_id:{type:'string'},visual_delta:{type:'integer',minimum:0,maximum:10},semantic_delta:{type:'integer',minimum:0,maximum:10},attention_delta:{type:'integer',minimum:0,maximum:10},expectation_delta:{type:'integer',minimum:0,maximum:10},change_level:{type:'integer',enum:[1,2,3]},perceptually_distinct:{type:'boolean'},dominant_state:{type:'string'},reading_burden:{type:'integer',minimum:0,maximum:10},failure_reasons:{type:'array',items:{type:'string'}}},required:['beat_id','visual_delta','semantic_delta','attention_delta','expectation_delta','change_level','perceptually_distinct','dominant_state','reading_burden','failure_reasons']}},hook_strong_event:{type:'boolean'},long_scene_reengagement:{type:'boolean'},evidence_payload_complete_at_beat:{anyOf:[{type:'string'},{type:'null'}]},post_information_linger:{type:'boolean'},mechanism_visually_underpowered:{type:'boolean'},microcopy_overload:{type:'boolean'},payoff_visual_impact:{type:'integer',minimum:0,maximum:10},payoff_as_end_card:{type:'boolean'},motion_spatial:{type:'object',additionalProperties:false,properties:{topology_change:{type:'integer',minimum:0,maximum:10},spatial_change:{type:'integer',minimum:0,maximum:10},relationship_change:{type:'integer',minimum:0,maximum:10},focal_change:{type:'integer',minimum:0,maximum:10},object_state_change:{type:'integer',minimum:0,maximum:10},semantic_readability:{type:'integer',minimum:0,maximum:10},centered_composition:{type:'boolean'},cardless_card:{type:'boolean'},generic_motion_anatomy:{type:'boolean'},source_viewport_traversed:{type:'boolean'},source_orientation_preserved:{type:'boolean'},limitation_directed:{type:'boolean'},payoff_complexity_reduced:{type:'boolean'},diagnostic_overlay_text:{type:'array',items:{type:'string'}},motion_summary:{type:'string'}},required:['topology_change','spatial_change','relationship_change','focal_change','object_state_change','semantic_readability','centered_composition','cardless_card','generic_motion_anatomy','source_viewport_traversed','source_orientation_preserved','limitation_directed','payoff_complexity_reduced','diagnostic_overlay_text','motion_summary']},object_identity:objectIdentitySchema},required:['scene_id','summary','beats','hook_strong_event','long_scene_reengagement','evidence_payload_complete_at_beat','post_information_linger','mechanism_visually_underpowered','microcopy_overload','payoff_visual_impact','payoff_as_end_card','motion_spatial','object_identity']} as const;

export const visionQaPerceptualScene=async(input:{client:OpenAiLike;model:string;manifest:AnimationManifest;sceneId:string;samples:PerceptualSample[]})=>{
  const scene=input.manifest.scenes.find((item)=>item.id===input.sceneId)!;const contract=scene.retentionExecution!;const spatial=scene.representationPlan?.spatial_motion;const identity=scene.representationPlan?.embodiment;const content:any[]=[{type:'input_text',text:`Scene ${scene.id}, duration ${(scene.endSeconds-scene.startSeconds).toFixed(2)}s, source ${scene.hybridSource?.choice??'CODE_NATIVE'}. Ordered images are actual PRODUCTION MP4 states, one per sampled beat. Independently compare what a viewer sees. Beat ids in order: ${input.samples.map((item)=>item.beat_id).join(', ')}. Level 1=cosmetic only; Level 2=clear perceptual/composition/focal/relationship change; Level 3=meaning or interpretation transforms. Do not credit opacity, minor scale, drift, glow, camera movement without new information, or text appearing alone. Check topology/spatial/relationship/focal/object-state change, semantic object identity before/after motion, visible identity channels, label dependency, source authority, unknown-as-unresolved-space, fact/inference distinction, editorial compensation, and Vietnamese production-language consistency (original source English is allowed). Planned intent is context only, never proof: beats=${contract.beats.map((beat)=>`${beat.beat_id}:${beat.purpose}`).join('; ')}; planned events=${spatial?.events.map(event=>`${event.event_type}:${event.intended_realization.viewer_should_notice}`).join('; ')??'none'}; planned topology=${spatial?JSON.stringify(spatial.topology):'none'}; planned identity=${identity?JSON.stringify(identity.signatures):'none'}`}];
  for(const sample of input.samples)content.push({type:'input_image',detail:'high',image_url:`data:image/jpeg;base64,${readFileSync(sample.path).toString('base64')}`});
  const response=await input.client.responses.create({model:input.model,instructions:'You are CKAI Perceptual, Motion/Spatial and Semantic Object Identity QA. Judge only actual supplied production pixels and ordered viewer-perceived differences. Renderer execution, signatures and plan descriptions earn no credit. Be strict about anonymous geometry, color-only identity, labels manufacturing meaning, identity lost in motion/transformation, generic centered choreography, editorial English in Vietnamese production, static evidence viewports, static hooks and checkmark/text-only payoffs.',input:[{role:'user',content}],text:{format:{type:'json_schema',name:'ckai_perceptual_scene_qa',strict:true,schema:sceneSchema}}} as any);
  if(!response.output_text?.trim())throw new Error(`Perceptual Vision returned no output for ${scene.id}`);return {qa:JSON.parse(response.output_text) as PerceptualSceneVisionQa,usage:response.usage?JSON.parse(JSON.stringify(response.usage)) as Record<string,unknown>:{},responseId:response.id};
};

export const runPerceptualProgressionQa=async(input:{client:OpenAiLike;model:string;videoPath:string;manifest:AnimationManifest;outputDir:string})=>{
  const samples=extractPerceptualSamples(input.videoPath,input.manifest,input.outputDir);const scenes:PerceptualSceneQa[]=[];const usage:Array<Record<string,unknown>>=[];
  for(const scene of input.manifest.scenes){const result=await visionQaPerceptualScene({client:input.client,model:input.model,manifest:input.manifest,sceneId:scene.id,samples:samples.filter((item)=>item.scene_id===scene.id)});usage.push(result.usage);scenes.push(normalizePerceptualSceneQa(input.manifest,result.qa));}
  const failures=[...new Set(scenes.flatMap((scene)=>scene.failure_classes))];const strongest=scenes.flatMap((scene)=>scene.beats).filter((beat)=>beat.change_level===3&&beat.perceptually_distinct).map((beat)=>beat.beat_id);const weak=scenes.flatMap((scene)=>scene.beats).filter((beat)=>!beat.perceptually_distinct).map((beat)=>beat.beat_id);const middle=scenes.slice(1,-1);const contractSha=sha(Buffer.from(JSON.stringify(input.manifest.scenes.map((scene)=>({id:scene.id,retentionExecution:scene.retentionExecution,semanticMechanism:scene.semanticMechanism,source:scene.hybridSource?.choice})))));const result:PerceptualProgressionQa={version:1,actual_binary:true,model:input.model,video_path:input.videoPath,video_sha256:sha(readFileSync(input.videoPath)),contract_sha256:contractSha,sampling_strategy:'ONE_ORDERED_STATE_PER_BEAT_MAX_FOUR_PER_SCENE',vision_calls:scenes.length,sampled_images:samples.length,scenes,strongest_beats:strongest,weak_beats:weak,long_same_state_windows:scenes.filter((scene)=>scene.long_same_state_seconds>=3).map((scene)=>({scene_id:scene.scene_id,seconds:scene.long_same_state_seconds})),hook_distinct_events:scenes[0]?.beats.filter((beat)=>beat.perceptually_distinct&&beat.change_level>=2).length??0,mid_video_reengagement:middle.every((scene)=>scene.long_scene_reengagement||scene.long_same_state_seconds<3),payoff_visual_impact:scenes.at(-1)?.payoff_visual_impact??0,verdict:scenes.every((scene)=>scene.verdict==='PASS')?'PASS':'FAIL',failure_classes:failures,usage};return {qa:result,samples:samples.map((sample)=>({...sample,path:basename(sample.path)}))};
};
