import type {AnimationManifest} from '../../animation/src/model';
import type {PerceptualProgressionQa} from './perceptual-qa';
import {validateRepresentationPlans} from './representation';

export const REPRESENTATION_FAILURE_CLASSES=['REPRESENTATION_CAPABILITY_MISSING','PROCESS_EVENT_NOT_VISUALLY_REALIZED','OBJECT_STATE_NOT_PERCEPTIBLE','RELATIONSHIP_NOT_PERCEPTIBLE','LABEL_CARRYING_SEMANTIC_LOAD','PROCESS_COLLAPSED_TO_CARD_LAYOUT','SCENE_ROLE_GRAMMAR_MISMATCH','CROSS_SCENE_MOTIF_BROKEN','EVIDENCE_PRESENTATION_MISLEADING','EVIDENCE_TOO_DENSE_TO_READ','EVIDENCE_PROVENANCE_INCOMPLETE','EVIDENCE_REGION_NOT_PERCEPTIBLE','ANNOTATION_CONFUSED_WITH_SOURCE','EVIDENCE_CONTEXT_LOST','EVIDENCE_PAYLOAD_COMPLETE_BUT_SCENE_CONTINUES','DERIVED_VISUAL_NOT_DISCLOSED','HOOK_NO_MEANINGFUL_EVENT','HOOK_TEXT_DEPENDENT','HOOK_PROMISE_UNCLEAR','HOOK_BODY_GRAMMAR_FALLBACK','PAYOFF_NOT_EARNED','PAYOFF_NO_VISUAL_RESOLUTION','PAYOFF_TEXT_ONLY','PAYOFF_CALLBACK_MISSING','PAYOFF_EXCESSIVE_HOLD','REPRESENTATION_GRAMMAR_FATIGUE','REPLAN_ANATOMY_NOT_DISTINCT','CREATIVE_REPLAN_DISTANCE_TOO_LOW','BEST_ROUND_NOT_SELECTED'] as const;
export type RepresentationFailureClass=typeof REPRESENTATION_FAILURE_CLASSES[number];
export type ActualRepresentationQa={version:1;actual_binary:true;verdict:'PASS'|'FAIL';scenes:Array<{scene_id:string;grammar:string;renderer:string;anatomy:string;planned_events:string[];realized_event_ratio:number;failures:RepresentationFailureClass[];evidence:{mode:string|null;regions:number;integrity:'PASS'|'FAIL'};hook:'PASS'|'FAIL'|'N/A';payoff:'PASS'|'FAIL'|'N/A'}>;anatomy_sequence:string[];failures:RepresentationFailureClass[]};

const round=(n:number)=>Number(n.toFixed(3));
export const evaluateActualRepresentation=(manifest:AnimationManifest,perceptual:PerceptualProgressionQa):ActualRepresentationQa=>{
  const structural=validateRepresentationPlans(manifest);const scenes=manifest.scenes.map(scene=>{const plan=scene.representationPlan;const pixel=perceptual.scenes.find(item=>item.scene_id===scene.id);const failures:RepresentationFailureClass[]=[];if(!plan){failures.push('REPRESENTATION_CAPABILITY_MISSING');return {scene_id:scene.id,grammar:'missing',renderer:'missing',anatomy:'missing',planned_events:[],realized_event_ratio:0,failures,evidence:{mode:null,regions:0,integrity:'FAIL' as const},hook:'N/A' as const,payoff:'N/A' as const};}
    for(const failure of plan.compile_failures)if(REPRESENTATION_FAILURE_CLASSES.includes(failure as RepresentationFailureClass))failures.push(failure as RepresentationFailureClass);
    const strong=pixel?.beats.filter(beat=>beat.perceptually_distinct&&beat.change_level>=2).length??0;const ratio=plan.events.length?Math.min(1,strong/Math.min(plan.events.length,pixel?.beats.length??plan.events.length)):0;
    if(ratio<.5)failures.push('PROCESS_EVENT_NOT_VISUALLY_REALIZED');if((pixel?.mechanism_visually_underpowered??false)&&plan.objects.length)failures.push('OBJECT_STATE_NOT_PERCEPTIBLE');if((pixel?.mechanism_visually_underpowered??false)&&plan.relationships.length)failures.push('RELATIONSHIP_NOT_PERCEPTIBLE');if(pixel?.microcopy_overload||pixel?.beats.some(beat=>beat.reading_burden>=7))failures.push('LABEL_CARRYING_SEMANTIC_LOAD');if(/card|slide|grid|box/i.test(pixel?.summary??'')&&(pixel?.mechanism_visually_underpowered??false))failures.push('PROCESS_COLLAPSED_TO_CARD_LAYOUT');
    if(plan.retention_role==='HOOK'){if(!pixel?.hook_strong_event)failures.push('HOOK_NO_MEANINGFUL_EVENT');if((pixel?.beats[0]?.reading_burden??0)>=5||/text|headline|typograph/i.test(pixel?.summary??''))failures.push('HOOK_TEXT_DEPENDENT');if(plan.representation.renderer==='FilterClassificationRenderer')failures.push('HOOK_BODY_GRAMMAR_FALLBACK');}
    if(plan.retention_role==='PAYOFF'){if(pixel?.payoff_as_end_card)failures.push('PAYOFF_TEXT_ONLY');if((pixel?.payoff_visual_impact??0)<7)failures.push('PAYOFF_NO_VISUAL_RESOLUTION');if(!plan.hook_payoff_contract)failures.push('PAYOFF_CALLBACK_MISSING');if((pixel?.long_same_state_seconds??0)>3)failures.push('PAYOFF_EXCESSIVE_HOLD');}
    if(plan.source_type==='REAL_EVIDENCE'){if(!plan.evidence?.regions.length)failures.push('EVIDENCE_PROVENANCE_INCOMPLETE');if((pixel?.beats.some(beat=>beat.reading_burden>=8)))failures.push('EVIDENCE_TOO_DENSE_TO_READ');if(strong===0)failures.push('EVIDENCE_REGION_NOT_PERCEPTIBLE');if(pixel?.post_information_linger)failures.push('EVIDENCE_PAYLOAD_COMPLETE_BUT_SCENE_CONTINUES');if(plan.evidence?.mode==='DERIVED_FROM_EVIDENCE'&&plan.evidence.annotation_style!=='CKAI_EDITORIAL_OVERLAY')failures.push('DERIVED_VISUAL_NOT_DISCLOSED');}
    return {scene_id:scene.id,grammar:plan.grammar,renderer:plan.representation.renderer,anatomy:plan.representation.anatomy,planned_events:plan.events.map(event=>event.type),realized_event_ratio:round(ratio),failures:[...new Set(failures)],evidence:{mode:plan.evidence?.mode??null,regions:plan.evidence?.regions.length??0,integrity:failures.some(f=>['EVIDENCE_PRESENTATION_MISLEADING','EVIDENCE_PROVENANCE_INCOMPLETE','ANNOTATION_CONFUSED_WITH_SOURCE','EVIDENCE_CONTEXT_LOST','DERIVED_VISUAL_NOT_DISCLOSED'].includes(f))?'FAIL' as const:'PASS' as const},hook:plan.retention_role==='HOOK'?(failures.some(f=>f.startsWith('HOOK_'))?'FAIL' as const:'PASS' as const):'N/A' as const,payoff:plan.retention_role==='PAYOFF'?(failures.some(f=>f.startsWith('PAYOFF_'))?'FAIL' as const:'PASS' as const):'N/A' as const};});
  const anatomy=manifest.scenes.map(scene=>scene.representationPlan?.representation.anatomy??'missing');for(let index=2;index<anatomy.length;index++)if(anatomy[index]===anatomy[index-1]&&anatomy[index]===anatomy[index-2])scenes[index]!.failures.push('REPRESENTATION_GRAMMAR_FATIGUE');const motifPlans=manifest.scenes.map(scene=>scene.representationPlan).filter(Boolean);if(motifPlans.length&&(!motifPlans[0]?.persistent_motifs.length||!motifPlans.at(-1)?.hook_payoff_contract))scenes.at(-1)?.failures.push('CROSS_SCENE_MOTIF_BROKEN');const failures=[...new Set([...structural.failures.filter(f=>REPRESENTATION_FAILURE_CLASSES.includes(f as RepresentationFailureClass)) as RepresentationFailureClass[],...scenes.flatMap(scene=>scene.failures)])];return {version:1,actual_binary:true,verdict:failures.length?'FAIL':'PASS',scenes,anatomy_sequence:anatomy,failures};
};
