import {existsSync,readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import type {AnimationManifest,Scene} from '../../animation/src/model';
import {PROCESS_EVENT_TYPES,RELATIONSHIP_TYPES,SEMANTIC_OBJECT_TYPES,type EvidenceProcess,type ProcessEvent,type ProcessObject,type ProcessPlan,type RendererId,type RepresentationDecision,type RepresentationGrammar,type SceneRole,type SourceType,type VisualAnatomy} from '../../animation/src/representation';
import {compileSpatialMotionPlan} from './spatial-motion';
import {compileEmbodimentPlan} from './embodiment';
import type {EmbodimentMaterial} from '../../animation/src/embodiment';

export type RendererCapability={id:RendererId;supports:{object_types:string[];relationship_types:string[];events:string[];scene_roles:SceneRole[];source_types:SourceType[]};perceptual_capabilities:{strong_events:string[];transformation_strength:'HIGH'|'MEDIUM';text_dependency:'LOW'|'MEDIUM';object_motion_strength:'HIGH'|'MEDIUM';evidence_readability:'HIGH'|'NONE';recommended_hold:number};spatial_capabilities:{supported_topologies:string[];supported_regions:string[];max_legible_objects:number;branch_depth:number;viewport_travel:boolean;topology_transitions:string[]};embodiment_capabilities:{supported_semantic_roles:string[];supported_material_types:string[];source_fragment_support:boolean;identity_preservation:boolean;lineage_support:boolean;label_dependency:'LOW'|'MEDIUM';max_distinct_role_count:number;abstraction_level_support:string[]};limitations:string[]};
const cap=(id:RendererId,source_types:SourceType[],events:string[],roles:SceneRole[],evidence_readability:'HIGH'|'NONE'='NONE'):RendererCapability=>({id,supports:{object_types:[...SEMANTIC_OBJECT_TYPES],relationship_types:[...RELATIONSHIP_TYPES],events,scene_roles:roles,source_types},perceptual_capabilities:{strong_events:events.slice(0,5),transformation_strength:'HIGH',text_dependency:'LOW',object_motion_strength:'HIGH',evidence_readability,recommended_hold:2.4},spatial_capabilities:{supported_topologies:id==='EvidenceNativeRenderer'?['SOURCE_VIEWPORT','REGION','PATH']:id==='FilterClassificationRenderer'?['FIELD','GATE','REGION','LANE']:id==='HypothesisBranchRenderer'?['FIELD','BRANCH','PATH','OUTSIDE_FIELD']:['FIELD','PATH','GAP','BRIDGE','ANCHOR','CONVERGENCE_TARGET'],supported_regions:['ACTIVE','VERIFIED','PROVISIONAL','UNKNOWN','REJECTED'],max_legible_objects:id==='EvidenceNativeRenderer'?4:6,branch_depth:id==='HypothesisBranchRenderer'?3:1,viewport_travel:id==='EvidenceNativeRenderer',topology_transitions:events},embodiment_capabilities:{supported_semantic_roles:[...SEMANTIC_OBJECT_TYPES],supported_material_types:id==='EvidenceNativeRenderer'?['SOURCE_FRAGMENT','PROPOSITION_FRAGMENT','STABLE_ANCHOR']:['SOURCE_FRAGMENT','PROPOSITION_FRAGMENT','STABLE_ANCHOR','DERIVED_TRAIL','BRANCH_CANDIDATE','NEGATIVE_SPACE_GAP','OUTCOME_MARKER','VARIABLE_CONTROL','STABILITY_FIELD','INTERACTIVE_GATE','EARNED_CONCLUSION','TERMINAL_PRINCIPLE','ABSTRACT_NODE'],source_fragment_support:true,identity_preservation:true,lineage_support:true,label_dependency:'LOW',max_distinct_role_count:id==='EvidenceNativeRenderer'?4:6,abstraction_level_support:id==='EvidenceNativeRenderer'?['LEVEL_1_REAL_SOURCE','LEVEL_2_RECOGNIZABLE_MATERIAL']:['LEVEL_1_REAL_SOURCE','LEVEL_2_RECOGNIZABLE_MATERIAL','LEVEL_3_SEMANTIC_DIAGRAMMATIC','LEVEL_4_ABSTRACT_NODE']},limitations:id==='EvidenceNativeRenderer'?['Never alter factual source pixels or disguise overlays as source content']:['Does not support raw evidence authority; source fragments are derived and retain lineage']});
const allRoles:SceneRole[]=['HOOK','CONTEXT','CONTRAST','PROOF','REVEAL','PAYOFF','CURIOSITY','ESCALATION','BREATH'];
export const RENDERER_CAPABILITY_REGISTRY:Record<RendererId,RendererCapability>={
  CausalRelationshipRenderer:cap('CausalRelationshipRenderer',['CODE_NATIVE','GENERATED_KEY_VISUAL'],['INTRODUCE','CONNECT','BREAK','BRANCH','REVEAL'],allRoles),
  FilterClassificationRenderer:cap('FilterClassificationRenderer',['CODE_NATIVE'],['INTRODUCE','FILTER','SPLIT','PROMOTE','REVEAL'],allRoles),
  HypothesisBranchRenderer:cap('HypothesisBranchRenderer',['CODE_NATIVE','GENERATED_KEY_VISUAL'],['INTRODUCE','BRANCH','REJECT','COLLAPSE','REVEAL'],allRoles),
  ConfidenceStateRenderer:cap('ConfidenceStateRenderer',['CODE_NATIVE'],['INTRODUCE','DEMOTE','REVEAL','VERIFY','TRANSFORM'],allRoles),
  EvidenceNativeRenderer:cap('EvidenceNativeRenderer',['REAL_EVIDENCE'],['REGION_FOCUS','REGION_REVEAL','CONTEXT_DIM','SOURCE_PAN','DETAIL_ZOOM','EVIDENCE_TRACE','ANNOTATION_ATTACH','LIMITATION_MARK'],['PROOF','CONTEXT','REVEAL'],'HIGH'),
  ConvergenceTransformationRenderer:cap('ConvergenceTransformationRenderer',['CODE_NATIVE','GENERATED_KEY_VISUAL'],['INTRODUCE','MERGE','TRANSFORM','RESOLVE','REVEAL'],allRoles),
};

const sourceOf=(scene:Scene):SourceType=>scene.hybridSource?.choice==='REAL_EVIDENCE'?'REAL_EVIDENCE':scene.hybridSource?.choice==='GENERATED_KEY_VISUAL'||scene.hybridSource?.choice==='CURATED_OR_GENERATED_KEY_VISUAL'?'GENERATED_KEY_VISUAL':'CODE_NATIVE';
const roleOf=(scene:Scene,index:number,total:number):SceneRole=>index===0?'HOOK':index===total-1?'PAYOFF':scene.artDirection?.proof.classification==='actual-proof'||scene.artDirection?.proof.classification==='visual-representation'?'PROOF':(scene.semanticMechanism?.family==='comparison'||scene.semanticMechanism?.family==='contradiction')?'CONTRAST':'CONTEXT';
const words=(value:string)=>value.trim().split(/\s+/u).filter(Boolean).length;
const labels=(scene:Scene)=>[...(scene.semanticMechanism?.entities??[]),...(scene.displayCopy?.split(/\n+/u)??[])].map(x=>x.trim()).filter(Boolean).slice(0,5);
const object=(id:string,type:ProcessObject['type'],label:string,state:ProcessObject['state'],shape:ProcessObject['visual_encoding']['shape'],stability:ProcessObject['visual_encoding']['stability'],accent:ProcessObject['visual_encoding']['accent']):ProcessObject=>({id,type,label,state,visual_encoding:{shape,stability,accent}});
const event=(id:string,at:number,type:ProcessEvent['type'],targets:string[],from_state:string,to_state:string,reason:string,notice:string,level:2|3=3):ProcessEvent=>({id,at,type,targets,from_state,to_state,semantic_reason:reason,perceptual_target:{minimum_change_level:level,viewer_should_notice:notice}});
const family=(scene:Scene,role:SceneRole,source:SourceType,round:number,rejected:VisualAnatomy[]):{grammar:RepresentationGrammar;renderer:RendererId;anatomy:VisualAnatomy}=>{
  if(source==='REAL_EVIDENCE')return {grammar:'EVIDENCE_PROOF',renderer:'EvidenceNativeRenderer',anatomy:round===0?'SOURCE_VIEWPORT':round===1?'EVIDENCE_TRACE_PATH':'EVIDENCE_REGION_FLOW'};
  if(role==='PAYOFF')return {grammar:'CONVERGENCE_PAYOFF',renderer:'ConvergenceTransformationRenderer',anatomy:round===0?'CONVERGENCE_FIELD':round===1?'TRANSFORMATION_PATH':'OBJECT_FLOW'};
  const mechanism=scene.semanticMechanism?.family;
  const progression=(base:{grammar:RepresentationGrammar;renderer:RendererId;anatomy:VisualAnatomy},first:{grammar:RepresentationGrammar;renderer:RendererId;anatomy:VisualAnatomy})=>round===0?base:round===1?first:{grammar:'TRANSFORMATION_STATE_CHANGE' as const,renderer:'ConvergenceTransformationRenderer' as const,anatomy:'TRANSFORMATION_PATH' as const};
  if(role==='HOOK'||source==='GENERATED_KEY_VISUAL')return progression({grammar:'CAUSAL_RELATIONSHIP',renderer:'CausalRelationshipRenderer',anatomy:source==='GENERATED_KEY_VISUAL'?'GENERATED_FRACTURE':'RELATIONSHIP_GRAPH'},{grammar:'HYPOTHESIS_BRANCHING',renderer:'HypothesisBranchRenderer',anatomy:'BRANCH_NETWORK'});
  if(['filtering','hierarchy','fact_vs_inference','elimination'].includes(mechanism??''))return round===0?{grammar:'FILTER_CLASSIFY',renderer:'FilterClassificationRenderer',anatomy:'OBJECT_FLOW'}:round===1?{grammar:'TRANSFORMATION_STATE_CHANGE',renderer:'ConvergenceTransformationRenderer',anatomy:'TRANSFORMATION_PATH'}:{grammar:'HYPOTHESIS_BRANCHING',renderer:'HypothesisBranchRenderer',anatomy:'BRANCH_NETWORK'};
  if(['hypothesis_branching','hidden_variable_reveal'].includes(mechanism??''))return progression({grammar:'HYPOTHESIS_BRANCHING',renderer:'HypothesisBranchRenderer',anatomy:'BRANCH_NETWORK'},{grammar:'CAUSAL_RELATIONSHIP',renderer:'CausalRelationshipRenderer',anatomy:'RELATIONSHIP_GRAPH'});
  if(mechanism==='confidence_uncertainty'||mechanism==='before_after'||mechanism==='state_transition')return progression({grammar:'CONFIDENCE_UNCERTAINTY',renderer:'ConfidenceStateRenderer',anatomy:'CONFIDENCE_FIELD'},{grammar:'CAUSAL_RELATIONSHIP',renderer:'CausalRelationshipRenderer',anatomy:'RELATIONSHIP_GRAPH'});
  return progression({grammar:'CAUSAL_RELATIONSHIP',renderer:'CausalRelationshipRenderer',anatomy:'RELATIONSHIP_GRAPH'},{grammar:'HYPOTHESIS_BRANCHING',renderer:'HypothesisBranchRenderer',anatomy:'BRANCH_NETWORK'});
};

const evidenceFor=(scene:Scene,repoRoot:string):EvidenceProcess|undefined=>{const asset=scene.hybridSource?.asset;if(!asset||sourceOf(scene)!=='REAL_EVIDENCE')return undefined;const path=resolve(repoRoot,asset.source);const raw=existsSync(path)?readFileSync(path,'utf8'):'';const lines=raw.split(/\r?\n/u).map(x=>x.trim()).filter(x=>x&&!x.startsWith('---')&&!x.startsWith('#')).slice(0,18);const excerpts=[lines.slice(0,5).join(' · '),lines.slice(5,11).join(' · '),lines.slice(11,17).join(' · ')];return {mode:'DERIVED_FROM_EVIDENCE',asset_id:asset.assetId,source:asset.source,provenance:asset.provenance,sha256:asset.sha256,regions:[{region_id:'REGION-CLAIM',semantic_role:'CLAIM',bounds:{x:.08,y:.12,width:.84,height:.2},viewer_should_notice:'The tested claim is visibly located in the canonical source.',source_excerpt:excerpts[0]||scene.displayCopy||'Canonical source claim'},{region_id:'REGION-SUPPORT',semantic_role:'SUPPORT',bounds:{x:.08,y:.38,width:.84,height:.27},viewer_should_notice:'The source lists variables/evidence still required.',source_excerpt:excerpts[1]||scene.artDirection?.supportingElements.join(' · ')||'Supporting evidence region'},{region_id:'REGION-LIMIT',semantic_role:'LIMITATION',bounds:{x:.08,y:.7,width:.84,height:.18},viewer_should_notice:'The evidence limit remains visible.',source_excerpt:excerpts[2]||scene.artDirection?.proof.truthLabel||'Evidence limitation'}],viewport:{source_asset_id:asset.assetId,focus_region:'REGION-CLAIM',surrounding_context:'Keep title, adjacent source lines and provenance visible.',zoom_level:1.08,context_visibility:.55},proof_hierarchy:{claim_being_tested:scene.displayCopy??scene.purpose,evidence_region:'REGION-SUPPORT',what_it_supports:'The direct-test record supports the reported behavior.',what_it_does_not_support:'It does not prove a universal causal conclusion.',remaining_uncertainty:'Other variables still require verification.'},annotation_style:'CKAI_EDITORIAL_OVERLAY',payload_complete_event:'LIMITATION_MARK'};};

export const validateCapability=(decision:RepresentationDecision,objects:ProcessObject[],events:ProcessEvent[],role:SceneRole,source:SourceType)=>{const capability=RENDERER_CAPABILITY_REGISTRY[decision.renderer];const failures:string[]=[];if(!capability||!capability.supports.source_types.includes(source)||!capability.supports.scene_roles.includes(role)||objects.some(item=>!capability.supports.object_types.includes(item.type))||events.some(item=>!capability.supports.events.includes(item.type)))failures.push('REPRESENTATION_CAPABILITY_MISSING');return failures;};
export const validateEmbodimentCapability=(plan:ProcessPlan)=>{const capability=RENDERER_CAPABILITY_REGISTRY[plan.representation.renderer],failures:string[]=[];if(!capability||!plan.embodiment)return ['EMBODIMENT_CAPABILITY_MISSING'];for(const object of plan.objects){const decision=plan.embodiment.decisions[object.id];if(!decision||!capability.embodiment_capabilities.supported_semantic_roles.includes(object.type)||!capability.embodiment_capabilities.supported_material_types.includes(decision.selected_material)||!capability.embodiment_capabilities.abstraction_level_support.includes(decision.selected_level)||(decision.selected_material==='SOURCE_FRAGMENT'&&!capability.embodiment_capabilities.source_fragment_support))failures.push('EMBODIMENT_CAPABILITY_MISSING');}return [...new Set(failures)];};

export const compileSceneRepresentation=(scene:Scene,index:number,total:number,repoRoot:string,options:{round?:number;recent_anatomies?:VisualAnatomy[];rejected_anatomies?:VisualAnatomy[];motif?:string}={}):ProcessPlan=>{
  const round=options.round??0,role=roleOf(scene,index,total),source=sourceOf(scene),rejected=options.rejected_anatomies??[];const selected=family(scene,role,source,round,rejected);const text=labels(scene);let objects:ProcessObject[]=[];let relationships:ProcessPlan['relationships']=[];let events:ProcessEvent[]=[];
  if(selected.grammar==='CAUSAL_RELATIONSHIP'){objects=[object('claim','CLAIM',text[0]??'Kết luận','PROVISIONAL','NODE','UNSTABLE','INK'),object('outcome','OUTCOME',text[1]??'Kết quả','ACTIVE','ORB','SOLID','AMBER'),object('gap','UNKNOWN','?','UNKNOWN','GATE','DOTTED','DANGER'),object('variable','VARIABLE',text[2]??'Biến khác','HIDDEN','ORB','DOTTED','MUTED')];relationships=[{id:'assumed-link',from:'claim',to:'outcome',type:'CAUSES',state:'UNVERIFIED'}];events=[event('introduce',0,'INTRODUCE',['claim','outcome'],'HIDDEN','ACTIVE','Expose the apparent causal pair.','Two distinct objects appear as a tempting relationship.'),event('connect',.24,'CONNECT',['assumed-link'],'POSSIBLE','UNVERIFIED','Make the assumption visible.','A provisional link visibly forms.',2),event('break',.48,'BREAK',['assumed-link'],'UNVERIFIED','BROKEN','The causal claim lacks evidence.','The assumed connection visibly snaps.'),event('reveal-gap',.66,'REVEAL',['gap'],'HIDDEN','QUESTIONED','Expose the missing evidentiary interval.','A missing-evidence gate occupies the broken relationship.'),event('branch-variable',.82,'BRANCH',['variable'],'HIDDEN','PROVISIONAL','Keep alternate explanations open.','A competing variable branches into view.')];}
  else if(selected.grammar==='FILTER_CLASSIFY'){objects=[object('raw','CLAIM',text[0]??'Dòng trả lời','ACTIVE','TOKEN','UNSTABLE','INK'),object('fact','FACT',text[1]??'Dữ kiện','HIDDEN','TOKEN','SOLID','INK'),object('inference','INFERENCE',text[2]??'Suy luận','HIDDEN','TOKEN','DOTTED','AMBER'),object('unknown','UNKNOWN',text[3]??'Chưa biết','HIDDEN','TOKEN','UNSTABLE','DANGER'),object('gate','VERIFICATION_GATE','Kiểm chứng','HIDDEN','GATE','SOLID','AMBER')];events=[event('raw-in',0,'INTRODUCE',['raw'],'HIDDEN','ACTIVE','Show one mixed claim stream.','One mixed object enters.'),event('filter',.25,'FILTER',['raw'],'ACTIVE','QUESTIONED','Pass the claim through a semantic filter.','The raw object visibly enters a filter aperture.'),event('split',.5,'SPLIT',['raw','fact','inference','unknown'],'ACTIVE','INTRODUCED','Separate semantic states.','One object physically becomes three different states.'),event('verify-fact',.7,'PROMOTE',['fact'],'INTRODUCED','VERIFIED','Stabilize observable facts.','The fact locks while provisional objects remain unstable.'),event('gate',.84,'REVEAL',['gate'],'HIDDEN','ACTIVE','Open the verification path.','Uncertain objects flow toward a verification gate.')];}
  else if(selected.grammar==='HYPOTHESIS_BRANCHING'){objects=[object('outcome','OUTCOME',text[0]??'Kết quả','ACTIVE','ORB','SOLID','AMBER'),...['h1','h2','h3'].map((id,i)=>object(id,'HYPOTHESIS',text[i+1]??`Giả thuyết ${i+1}`,'PROVISIONAL','NODE','DOTTED',i===0?'INK':'MUTED'))];relationships=['h1','h2','h3'].map(id=>({id:`branch-${id}`,from:'outcome',to:id,type:'BRANCHES_TO' as const,state:'POSSIBLE' as const}));events=[event('outcome',0,'INTRODUCE',['outcome'],'HIDDEN','ACTIVE','Begin from the observed outcome.','One outcome appears before explanations.'),event('branch',.25,'BRANCH',['h1','h2','h3'],'HIDDEN','PROVISIONAL','Expose competing explanations.','Three paths visibly diverge.'),event('reject',.53,'REJECT',['h2'],'PROVISIONAL','REJECTED','Evidence weakens one explanation.','One branch visibly collapses.'),event('collapse',.7,'COLLAPSE',['h3'],'PROVISIONAL','DEEMPHASIZED','Keep only viable candidates.','A second path retracts without declaring certainty.'),event('survivor',.86,'REVEAL',['h1'],'PROVISIONAL','QUESTIONED','The surviving hypothesis remains provisional.','One dotted branch remains visibly unresolved.')];}
  else if(selected.grammar==='CONFIDENCE_UNCERTAINTY'){objects=[object('claim','CLAIM',text[0]??'Câu trả lời','ACTIVE','ORB','UNSTABLE','INK'),object('confidence','CONFIDENCE_STATE','Độ chắc chắn','PROVISIONAL','FIELD','DOTTED','AMBER'),object('evidence','EVIDENCE',text[1]??'Dữ kiện','HIDDEN','TOKEN','SOLID','INK')];events=[event('claim',0,'INTRODUCE',['claim'],'HIDDEN','ACTIVE','Show a fluent but unstable claim.','The claim visibly wobbles inside a dotted field.'),event('question',.28,'DEMOTE',['confidence'],'ACTIVE','PROVISIONAL','Expose uncertainty.','The certainty field loses stability.'),event('evidence',.52,'REVEAL',['evidence'],'HIDDEN','INTRODUCED','Bring evidence into the state model.','A solid evidence token enters.'),event('verify',.72,'VERIFY',['claim','confidence'],'PROVISIONAL','SUPPORTED','Evidence stabilizes only the supported portion.','Part of the field locks while uncertainty remains dotted.'),event('transform',.88,'TRANSFORM',['claim'],'SUPPORTED','RESOLVED','Resolve known versus guessed without binary overclaim.','The object becomes a mixed solid/dotted final state.')];}
  else if(selected.grammar==='EVIDENCE_PROOF'){objects=[object('source','SOURCE_REGION','Nguồn gốc','ACTIVE','REGION','SOLID','INK'),object('claim-region','SOURCE_REGION','Claim','HIDDEN','REGION','SOLID','AMBER'),object('support-region','SOURCE_REGION','Support','HIDDEN','REGION','SOLID','INK'),object('limit-region','SOURCE_REGION','Limit','HIDDEN','REGION','DOTTED','DANGER')];events=[event('source',0,'REGION_REVEAL',['source'],'HIDDEN','ACTIVE','Establish source authenticity before detail.','The real source context is visible.'),event('claim-focus',.22,'REGION_FOCUS',['claim-region'],'HIDDEN','ACTIVE','Locate the tested claim.','A clearly external CKAI bracket focuses the claim region.'),event('support',.46,'SOURCE_PAN',['support-region'],'HIDDEN','ACTIVE','Move through the supporting source region.','Viewport visibly moves while source context remains.'),event('trace',.66,'EVIDENCE_TRACE',['claim-region','support-region'],'ACTIVE','SUPPORTED','Connect claim to what the record supports.','An external trace connects two real regions.'),event('limit',.84,'LIMITATION_MARK',['limit-region'],'HIDDEN','QUESTIONED','Show what evidence does not prove.','A separate limitation overlay appears and the scene exits.')];}
  else {objects=[object('a','INFERENCE',text[0]??'Giả định','ACTIVE','TOKEN','UNSTABLE','MUTED'),object('b','FACT',text[1]??'Dữ kiện','ACTIVE','TOKEN','SOLID','INK'),object('c','UNKNOWN',text[2]??'Chưa biết','ACTIVE','TOKEN','DOTTED','DANGER'),object('principle','PRINCIPLE',scene.semanticMechanism?.insight_revealed??text.at(-1)??'Kiểm chứng','HIDDEN','FIELD','SOLID','AMBER')];events=[event('pieces',0,'INTRODUCE',['a','b','c'],'HIDDEN','ACTIVE','Recall unresolved body relationships.','Distinct prior states re-enter.'),event('merge',.3,'MERGE',['a','b','c'],'ACTIVE','RESOLVED','Converge the process without erasing uncertainty.','Objects visibly move into one verification path.'),event('transform',.57,'TRANSFORM',['a','b','c'],'ACTIVE','DEEMPHASIZED','Reduce entropy.','Complexity visibly collapses.'),event('resolve',.76,'RESOLVE',['principle'],'HIDDEN','RESOLVED','Land the earned principle.','One stable principle emerges from the convergence.'),event('callback',.9,'REVEAL',['principle'],'RESOLVED','RESOLVED','Close the hook relationship.','The opening gap motif visibly closes.')];}
  const capability=RENDERER_CAPABILITY_REGISTRY[selected.renderer];const recent=options.recent_anatomies??[];const novelty=recent.at(-1)===selected.anatomy?'LOW':recent.includes(selected.anatomy)?'MEDIUM':'HIGH';const alternatives=(Object.keys(RENDERER_CAPABILITY_REGISTRY) as RendererId[]).filter(id=>id!==selected.renderer).slice(0,2).map(renderer=>({grammar:selected.grammar,renderer,anatomy:selected.anatomy,reason:'Rejected because capability/source/role match is weaker or anatomy was recently used.'}));const decision:RepresentationDecision={...selected,selection_reason:`${selected.grammar} expresses ${scene.semanticMechanism?.family??scene.purpose} as viewer-visible process for ${role}; source remains ${source}.`,capability_match:'PASS',rejected_alternatives:alternatives,novelty_vs_recent_scenes:novelty,...(role==='HOOK'?{hook_family:'MISSING_LINK' as const}:{}),...(role==='PAYOFF'?{payoff_family:'CALLBACK' as const}:{})};const failures=validateCapability(decision,objects,events,role,source);decision.capability_match=failures.length?'FAIL':'PASS';const allLabels=text;const primary=words(allLabels[0]??''),support=allLabels.slice(1).reduce((sum,x)=>sum+words(x),0);const plan:ProcessPlan={version:1,scene_id:scene.id,grammar:selected.grammar,retention_role:role,source_type:source,representation:decision,objects,relationships,events,display_copy:{labels:allLabels,simultaneous_labels:Math.min(2,allLabels.length),primary_words:primary,supporting_words:support,reading_burden:primary+support>24?'HIGH':primary+support>12?'MEDIUM':'LOW'},persistent_motifs:[{id:options.motif??'missing_evidence_gap',introduced_in:'SC-01',callbacks:[scene.id],resolved_in:`SC-0${total}`}],hook_payoff_contract:role==='HOOK'||role==='PAYOFF'?{hook_question:'What is missing before this claim is defensible?',hook_visual_motif:'missing_evidence_gap',unresolved_relationship:'claim appears causally complete without evidence',payoff_resolution:'verification gate closes the unsupported path',payoff_visual_callback:'the gap becomes a resolved verification path',final_principle:'Do not rush to believe; verify.'}:undefined,evidence:evidenceFor(scene,repoRoot),compile_failures:failures};scene.representationPlan=plan;plan.embodiment=compileEmbodimentPlan(scene,[],0);plan.compile_failures.push(...plan.embodiment.compile_failures);return plan;
};

export const compileRepresentationPlans=(manifest:AnimationManifest,repoRoot:string,options:{round?:number;rejected_by_scene?:Record<string,VisualAnatomy[]>}={})=>{const recent:VisualAnatomy[]=[],recentMaterials:EmbodimentMaterial[]=[];for(const [index,scene] of manifest.scenes.entries()){const plan=compileSceneRepresentation(scene,index,manifest.scenes.length,repoRoot,{round:options.round,recent_anatomies:recent,rejected_anatomies:options.rejected_by_scene?.[scene.id]??[]});plan.material_source=scene.hybridSource?.asset?.source;scene.representationPlan=plan;plan.embodiment=compileEmbodimentPlan(scene,recentMaterials,0);plan.compile_failures=[...new Set([...plan.compile_failures,...plan.embodiment.compile_failures,...validateEmbodimentCapability(plan)])];plan.spatial_motion=compileSpatialMotionPlan(scene,'PRODUCTION');recent.push(plan.representation.anatomy);}return manifest;};

export type RepresentationQa={verdict:'PASS'|'FAIL';failures:string[];scene_results:Array<{scene_id:string;failures:string[]}>};
export const validateRepresentationPlans=(manifest:AnimationManifest):RepresentationQa=>{const scene_results=manifest.scenes.map(scene=>{const plan=scene.representationPlan;const failures:string[]=[];if(!plan)failures.push('REPRESENTATION_CAPABILITY_MISSING');else{failures.push(...plan.compile_failures);if(plan.display_copy.reading_burden==='HIGH'&&plan.display_copy.simultaneous_labels>2)failures.push('LABEL_CARRYING_SEMANTIC_LOAD');if(!plan.events.length)failures.push('PROCESS_EVENT_NOT_VISUALLY_REALIZED');if(plan.retention_role==='HOOK'&&!plan.events.some(e=>e.at<=.5&&e.perceptual_target.minimum_change_level===3))failures.push('HOOK_NO_MEANINGFUL_EVENT');if(plan.retention_role==='PAYOFF'&&!plan.events.some(e=>e.type==='RESOLVE'))failures.push('PAYOFF_NO_VISUAL_RESOLUTION');if(plan.source_type==='REAL_EVIDENCE'&&(!plan.evidence||!plan.evidence.regions.length))failures.push('EVIDENCE_PROVENANCE_INCOMPLETE');if(plan.evidence?.mode==='DERIVED_FROM_EVIDENCE'&&!plan.evidence.annotation_style)failures.push('DERIVED_VISUAL_NOT_DISCLOSED');}return {scene_id:scene.id,failures};});const failures=[...new Set(scene_results.flatMap(x=>x.failures))];return {verdict:failures.length?'FAIL':'PASS',failures,scene_results};};

export const creativeReplanDistance=(before:ProcessPlan,after:ProcessPlan):'LOW'|'MEDIUM'|'HIGH'=>before.representation.anatomy===after.representation.anatomy&&before.representation.renderer===after.representation.renderer?'LOW':before.grammar!==after.grammar&&before.representation.anatomy!==after.representation.anatomy?'HIGH':'MEDIUM';
export type CandidateScore={round:number;candidate_label?:string;repair_pass?:0|1;identity_repair_pass?:0|1;motion_repair_pass?:0|1;meaning_pass:boolean;evidence_pass:boolean;production_cleanliness?:boolean;production_language_pass?:boolean;hard_failures:number;identity_failures?:number;motion_spatial_failures?:number;creative_quality:number;perceived_beat_ratio:number;cost:number;video:string};
export const selectBestCandidate=(candidates:CandidateScore[])=>{if(!candidates.length)throw new Error('BEST_ROUND_NOT_SELECTED: no candidates');return [...candidates].sort((a,b)=>Number(b.meaning_pass)-Number(a.meaning_pass)||Number(b.evidence_pass)-Number(a.evidence_pass)||Number(b.production_cleanliness??true)-Number(a.production_cleanliness??true)||Number(b.production_language_pass??true)-Number(a.production_language_pass??true)||a.hard_failures-b.hard_failures||(a.identity_failures??0)-(b.identity_failures??0)||(a.motion_spatial_failures??0)-(b.motion_spatial_failures??0)||b.creative_quality-a.creative_quality||b.perceived_beat_ratio-a.perceived_beat_ratio||a.cost-b.cost||a.round-b.round||(a.identity_repair_pass??a.repair_pass??0)-(b.identity_repair_pass??b.repair_pass??0))[0]!;};
