import {spawnSync} from 'node:child_process';
import type {AnimationManifest} from '../../animation/src/model';
import type {VoicePlan} from '../../voice/src/model';
import {resolveFfmpeg} from '../../shared/media-tools';
import {inspectActualBinaryExperience,type ActualBinaryExperience,type MediaSpan} from '../../review/src/experience';
import type {PerceptualFailureClass,PerceptualProgressionQa} from './perceptual-qa';

export type RetentionV2Failure='UNMOTIVATED_SCENE_TAIL'|'COSMETIC_MOTION_ONLY'|'RETENTION_PLAN_EXECUTION_MISMATCH'|'LEGACY_VISUAL_BEHAVIOR'|'HERO_SCENE_QUALITY_DROP'|'VISUAL_PATTERN_FATIGUE'|'MID_VIDEO_RETENTION_COLLAPSE'|'SOURCE_SWITCH_QUALITY_GAP'|'FILLER_SCENE'|'PAYOFF_NOT_PREPARED'|PerceptualFailureClass;
export type ActualRetentionWindow={scene_id:string;beat_id:string;start:number;end:number;speech_activity:boolean;silence_duration:number;visual_activity:number;semantic_state_change:boolean;focal_change:boolean;planned_retention_beat:string;actual_retention_beat_detected:boolean;perceptually_distinct?:boolean;perceptual_change_level?:1|2|3;justification:string;risk:'LOW'|'MEDIUM'|'HIGH'|'FAIL';findings:RetentionV2Failure[]};
export type SceneExecutionSummary={scene_id:string;planned_beats:number;executed_beats:number;meaningful_state_changes:number;cosmetic_only_changes:number;perceptually_distinct_beats?:number;weak_beats?:number;perceived_beat_ratio?:number;scene_tail_seconds:number;scene_tail_risk:'LOW'|'MEDIUM'|'HIGH'|'FAIL';legacy_visual_behavior:boolean};
export type ActualRetentionTimelineV2={policy_id:'UNMOTIVATED_SILENCE_POLICY_V1';actual_binary:true;duration_seconds:number;sample_fps:number;activity_threshold:number;windows:ActualRetentionWindow[];scenes:SceneExecutionSummary[];suspicious_spans:Array<{start:number;end:number;risk:'HIGH'|'FAIL';findings:RetentionV2Failure[];reason:string}>;high_risk_silence_count:number;over_two_second_silence_count:number;longest_weak_progression_window:number;verdict:'PASS'|'FAIL';failure_classes:RetentionV2Failure[];experience:ActualBinaryExperience};
export type CreativeContinuityQa={scene_quality:Array<{scene_id:string;source:string;quality:number;executed_ratio:number;mechanism:string}>;largest_quality_drop:number;repeated_visual_mode:string|null;legacy_fallback_detected:boolean;body_retention_strength:number;hero_scene_quality_drop:boolean;visual_pattern_fatigue:boolean;mid_video_retention_collapse:boolean;source_switch_quality_gap:boolean;payoff_prepared:boolean;verdict:'PASS'|'FAIL';failure_classes:RetentionV2Failure[]};

const overlap=(a:{start:number;end:number},b:MediaSpan)=>Math.max(0,Math.min(a.end,b.endSeconds)-Math.max(a.start,b.startSeconds));
const median=(values:number[])=>{const sorted=[...values].sort((a,b)=>a-b);return sorted.length?sorted[Math.floor(sorted.length/2)]!:0;};
const round=(value:number)=>Number(value.toFixed(3));

const frameActivity=(path:string,sampleFps=3)=>{
  const width=54,height=96,size=width*height;const result=spawnSync(resolveFfmpeg(),['-hide_banner','-loglevel','error','-i',path,'-vf',`fps=${sampleFps},scale=${width}:${height},format=gray`,'-f','rawvideo','-pix_fmt','gray','-'],{encoding:null,timeout:180_000,maxBuffer:32*1024*1024});
  if(result.status!==0||!Buffer.isBuffer(result.stdout))throw new Error(`Actual MP4 visual activity decode failed: ${path}`);
  const output=result.stdout;const values:Array<{time:number;diff:number}>=[];
  for(let offset=size,index=1;offset+size<=output.length;offset+=size,index+=1){let sum=0;for(let pixel=0;pixel<size;pixel+=1)sum+=Math.abs(output[offset+pixel]!-output[offset-size+pixel]!);values.push({time:index/sampleFps,diff:sum/size});}
  const baseline=median(values.map((item)=>item.diff));const threshold=Math.max(3.2,baseline*2.35);
  return {sampleFps,values,threshold};
};

const activityIn=(values:Array<{time:number;diff:number}>,start:number,end:number)=>{const matches=values.filter((item)=>item.time>=start&&item.time<=end);return {average:matches.length?matches.reduce((sum,item)=>sum+item.diff,0)/matches.length:0,peak:Math.max(0,...matches.map((item)=>item.diff))};};
const sourceFor=(scene:AnimationManifest['scenes'][number])=>scene.hybridSource?.asset?.sourceType==='GENERATED'?'GENERATED_KEY_VISUAL':scene.hybridSource?.choice??'CODE_NATIVE';

export const classifySilenceRisk=(durationSeconds:number,meaningfulProgression:boolean,justified:boolean):'LOW'|'MEDIUM'|'HIGH'|'FAIL'=>{
  if(justified&&meaningfulProgression)return durationSeconds>2?'MEDIUM':'LOW';
  if(durationSeconds>2&&!meaningfulProgression)return 'FAIL';
  if(durationSeconds>1.5)return meaningfulProgression?'MEDIUM':'HIGH';
  if(durationSeconds>1)return meaningfulProgression?'LOW':'MEDIUM';
  return 'LOW';
};

export const analyzeActualRetentionV2=(path:string,manifest:AnimationManifest,voicePlan?:VoicePlan):ActualRetentionTimelineV2=>{
  const experience=inspectActualBinaryExperience(path);const visual=frameActivity(path);const windows:ActualRetentionWindow[]=[];const scenes:SceneExecutionSummary[]=[];
  for(const scene of manifest.scenes){
    const contract=scene.retentionExecution;const absoluteStart=scene.startSeconds;const segment=voicePlan?.segments.find((item)=>item.sceneId===scene.id);const speechEnd=segment?segment.slotStartSeconds+(segment.measuredDurationSeconds??segment.slotEndSeconds-segment.slotStartSeconds):scene.endSeconds;const tail=Math.max(0,scene.endSeconds-speechEnd);
    if(!contract){
      const silence=experience.silenceSpans.reduce((sum,span)=>sum+overlap({start:scene.startSeconds,end:scene.endSeconds},span),0);windows.push({scene_id:scene.id,beat_id:`${scene.id}-LEGACY`,start:scene.startSeconds,end:scene.endSeconds,speech_activity:silence<scene.endSeconds-scene.startSeconds-.1,silence_duration:round(silence),visual_activity:round(activityIn(visual.values,scene.startSeconds,scene.endSeconds).average),semantic_state_change:false,focal_change:false,planned_retention_beat:'MISSING',actual_retention_beat_detected:false,justification:'No runtime-enforced retention beat contract exists.',risk:'FAIL',findings:['LEGACY_VISUAL_BEHAVIOR','RETENTION_PLAN_EXECUTION_MISMATCH']});scenes.push({scene_id:scene.id,planned_beats:0,executed_beats:0,meaningful_state_changes:0,cosmetic_only_changes:1,scene_tail_seconds:round(tail),scene_tail_risk:tail>2?'FAIL':tail>1.5?'HIGH':tail>1?'MEDIUM':'LOW',legacy_visual_behavior:true});continue;
    }
    let executed=0;let cosmetic=0;
    contract.beats.forEach((beat,index)=>{
      const start=absoluteStart+beat.start,end=absoluteStart+beat.end;const silence=experience.silenceSpans.reduce((sum,span)=>sum+overlap({start,end},span),0);const activity=activityIn(visual.values,start,end);const boundary=index===0?activityIn(visual.values,start,Math.min(end,start+.65)):activityIn(visual.values,Math.max(scene.startSeconds,start-.45),Math.min(scene.endSeconds,start+.65));const detected=index===0?activity.average>=visual.threshold*.25:boundary.peak>=visual.threshold;const findings:RetentionV2Failure[]=[];const duration=end-start;
      if(!detected&&duration>2.5)findings.push('COSMETIC_MOTION_ONLY');if(!detected&&index>0)findings.push('RETENTION_PLAN_EXECUTION_MISMATCH');if(silence>2&&!detected)findings.push('COSMETIC_MOTION_ONLY');
      const justified=contract.pause_budget.justified_pauses.some((pause)=>absoluteStart+pause.start<=start+.05&&absoluteStart+pause.end>=end-.05);const silenceRisk=classifySilenceRisk(silence,detected,justified);const risk:ActualRetentionWindow['risk']=!detected&&duration>4?'FAIL':!detected&&duration>2.5?'HIGH':!detected&&index>0&&silenceRisk==='LOW'?'MEDIUM':silenceRisk;if(detected)executed+=1;else cosmetic+=1;
      windows.push({scene_id:scene.id,beat_id:beat.beat_id,start:round(start),end:round(end),speech_activity:silence<duration-.1,silence_duration:round(silence),visual_activity:round(activity.average),semantic_state_change:detected,focal_change:boundary.peak>=visual.threshold,planned_retention_beat:beat.purpose,actual_retention_beat_detected:detected,justification:justified?contract.pause_budget.justified_pauses.find((pause)=>absoluteStart+pause.start<=start+.05&&absoluteStart+pause.end>=end-.05)!.basis:detected?beat.visual_state_change:'No actual-binary focal/state-change peak detected near the planned beat.',risk,findings:[...new Set(findings)]});
    });
    const tailActivity=activityIn(visual.values,speechEnd,scene.endSeconds);const hasTailProgress=contract.beats.some((beat,index)=>index>0&&absoluteStart+beat.start>=speechEnd-.15&&windows.find((window)=>window.beat_id===beat.beat_id)?.actual_retention_beat_detected);const tailRisk:SceneExecutionSummary['scene_tail_risk']=tail>2&&!hasTailProgress?'FAIL':tail>1.5&&!hasTailProgress?'HIGH':tail>1&&!hasTailProgress?'MEDIUM':'LOW';if(tailRisk==='FAIL'||tailRisk==='HIGH')windows.push({scene_id:scene.id,beat_id:`${scene.id}-TAIL`,start:round(speechEnd),end:round(scene.endSeconds),speech_activity:false,silence_duration:round(tail),visual_activity:round(tailActivity.average),semantic_state_change:hasTailProgress,focal_change:hasTailProgress,planned_retention_beat:'EXIT',actual_retention_beat_detected:hasTailProgress,justification:hasTailProgress?'A planned semantic state closes during the narration tail.':'Narration is complete and no further semantic progression is detected.',risk:tailRisk,findings:['UNMOTIVATED_SCENE_TAIL']});
    scenes.push({scene_id:scene.id,planned_beats:contract.beats.length,executed_beats:executed,meaningful_state_changes:executed,cosmetic_only_changes:cosmetic,scene_tail_seconds:round(tail),scene_tail_risk:tailRisk,legacy_visual_behavior:false});
  }
  const suspicious=windows.filter((window)=>window.risk==='HIGH'||window.risk==='FAIL').map((window)=>({start:window.start,end:window.end,risk:window.risk as 'HIGH'|'FAIL',findings:window.findings,reason:window.justification}));const failures=[...new Set(suspicious.flatMap((item)=>item.findings))];if(scenes.some((scene)=>scene.legacy_visual_behavior))failures.push('LEGACY_VISUAL_BEHAVIOR');
  return {policy_id:'UNMOTIVATED_SILENCE_POLICY_V1',actual_binary:true,duration_seconds:round(experience.durationSeconds),sample_fps:visual.sampleFps,activity_threshold:round(visual.threshold),windows,scenes,suspicious_spans:suspicious,high_risk_silence_count:experience.silenceSpans.filter((span)=>span.durationSeconds>1.5).length,over_two_second_silence_count:experience.silenceSpans.filter((span)=>span.durationSeconds>2).length,longest_weak_progression_window:round(Math.max(0,...suspicious.map((item)=>item.end-item.start))),verdict:suspicious.some((item)=>item.risk==='FAIL')||failures.includes('RETENTION_PLAN_EXECUTION_MISMATCH')?'FAIL':'PASS',failure_classes:[...new Set(failures)] as RetentionV2Failure[],experience};
};

export const applyPerceptualProgressionToTimeline=(timeline:ActualRetentionTimelineV2,perceptual:PerceptualProgressionQa):ActualRetentionTimelineV2=>{
  const copy=structuredClone(timeline);for(const scene of perceptual.scenes){const summary=copy.scenes.find((item)=>item.scene_id===scene.scene_id);if(summary){summary.perceptually_distinct_beats=scene.perceptually_distinct_beats;summary.weak_beats=scene.weak_beats;summary.perceived_beat_ratio=scene.perceived_beat_ratio;summary.meaningful_state_changes=scene.perceptually_distinct_beats;summary.cosmetic_only_changes=scene.weak_beats;}for(const beat of scene.beats){const window=copy.windows.find((item)=>item.beat_id===beat.beat_id);if(!window)continue;window.perceptually_distinct=beat.perceptually_distinct;window.perceptual_change_level=beat.change_level;if(!beat.perceptually_distinct){window.findings=[...new Set<RetentionV2Failure>([...window.findings,'BEAT_EXECUTED_BUT_NOT_PERCEPTUALLY_DISTINCT'])];window.risk=window.end-window.start>4?'FAIL':'HIGH';window.justification=beat.failure_reasons.join('; ')||'Runtime event executed, but sampled actual MP4 states were not perceptually distinct.';}}}
  for(const scene of perceptual.scenes.filter((item)=>item.long_same_state_seconds>5)){const source=copy.windows.find((item)=>item.scene_id===scene.scene_id&&!item.perceptually_distinct);if(source)copy.suspicious_spans.push({start:source.start,end:round(source.start+scene.long_same_state_seconds),risk:'FAIL',findings:['PERCEPTUAL_HOLD_TOO_LONG'],reason:`Dominant viewer-perceived state holds for ${scene.long_same_state_seconds}s.`});}
  copy.suspicious_spans.push(...copy.windows.filter((item)=>item.risk==='HIGH'||item.risk==='FAIL').filter((item)=>!copy.suspicious_spans.some((span)=>span.start===item.start&&span.end===item.end)).map((item)=>({start:item.start,end:item.end,risk:item.risk as 'HIGH'|'FAIL',findings:item.findings as RetentionV2Failure[],reason:item.justification})));
  copy.failure_classes=[...new Set([...copy.failure_classes,...perceptual.failure_classes,...copy.windows.flatMap((item)=>item.findings)])];copy.longest_weak_progression_window=round(Math.max(copy.longest_weak_progression_window,...perceptual.scenes.map((scene)=>scene.long_same_state_seconds)));copy.verdict=copy.verdict==='PASS'&&perceptual.verdict==='PASS'?'PASS':'FAIL';return copy;
};

export const evaluateCreativeContinuity=(manifest:AnimationManifest,timeline:ActualRetentionTimelineV2):CreativeContinuityQa=>{
  const sceneQuality=manifest.scenes.map((scene)=>{const execution=timeline.scenes.find((item)=>item.scene_id===scene.id)!;const ratio=execution.planned_beats?(execution.perceptually_distinct_beats??execution.executed_beats)/execution.planned_beats:0;const source=sourceFor(scene);const mechanism=scene.semanticMechanism?.family??(source==='GENERATED_KEY_VISUAL'?'generated focal progression':source==='REAL_EVIDENCE'?'progressive evidence':'missing');const base=source==='GENERATED_KEY_VISUAL'?9:source==='REAL_EVIDENCE'?8:scene.semanticMechanism?8:3;return{scene_id:scene.id,source,quality:Math.max(1,Math.round(base*ratio)),executed_ratio:round(ratio),mechanism};});
  const drops=sceneQuality.slice(1).map((scene,index)=>sceneQuality[index]!.quality-scene.quality);const largest=Math.max(0,...drops);const modes=manifest.scenes.map((scene)=>`${sourceFor(scene)}:${scene.artDirection?.visualMode??'unknown'}`);let repeated:string|null=null;for(let index=2;index<modes.length;index++)if(modes[index]===modes[index-1]&&modes[index-1]===modes[index-2])repeated=modes[index]!;
  const heroDrop=sceneQuality[0]!.quality-Math.min(...sceneQuality.slice(1).map((item)=>item.quality))>=4;const pattern=Boolean(repeated)||manifest.scenes.filter((scene)=>sourceFor(scene)==='CODE_NATIVE'&&!scene.semanticMechanism).length>=2;const middleStart=manifest.totalSeconds*.2,middleEnd=manifest.totalSeconds*.7;const middle=timeline.windows.filter((window)=>window.start<middleEnd&&window.end>middleStart);const midCollapse=middle.length>0&&middle.filter((window)=>window.actual_retention_beat_detected&&['CONTRAST','PROOF','REVEAL','TRANSFORM'].includes(window.planned_retention_beat)).length<2;const sourceGap=manifest.scenes.slice(1).some((scene,index)=>sourceFor(scene)!==sourceFor(manifest.scenes[index]!)&&Math.abs(sceneQuality[index+1]!.quality-sceneQuality[index]!.quality)>=4);const payoff=timeline.windows.some((window)=>window.planned_retention_beat==='PAYOFF'&&window.actual_retention_beat_detected)&&timeline.windows.some((window)=>['QUESTION','CONTRAST','PROOF','REVEAL','TRANSFORM'].includes(window.planned_retention_beat)&&window.actual_retention_beat_detected);
  const failures:RetentionV2Failure[]=[];if(heroDrop)failures.push('HERO_SCENE_QUALITY_DROP');if(pattern)failures.push('VISUAL_PATTERN_FATIGUE');if(midCollapse)failures.push('MID_VIDEO_RETENTION_COLLAPSE');if(sourceGap)failures.push('SOURCE_SWITCH_QUALITY_GAP');if(!payoff)failures.push('PAYOFF_NOT_PREPARED');if(timeline.failure_classes.includes('LEGACY_VISUAL_BEHAVIOR'))failures.push('LEGACY_VISUAL_BEHAVIOR');
  return {scene_quality:sceneQuality,largest_quality_drop:largest,repeated_visual_mode:repeated,legacy_fallback_detected:timeline.failure_classes.includes('LEGACY_VISUAL_BEHAVIOR'),body_retention_strength:sceneQuality.length>1?round(sceneQuality.slice(1).reduce((sum,item)=>sum+item.quality,0)/(sceneQuality.length-1)):sceneQuality[0]!.quality,hero_scene_quality_drop:heroDrop,visual_pattern_fatigue:pattern,mid_video_retention_collapse:midCollapse,source_switch_quality_gap:sourceGap,payoff_prepared:payoff,verdict:failures.length?'FAIL':'PASS',failure_classes:[...new Set(failures)]};
};
