import type {AnimationManifest,Scene} from '../../animation/src/model';
import type {ProcessEvent,ProcessPlan} from '../../animation/src/representation';
import type {EvidenceCameraPlan,FailureOrigin,GeometryPoint,MotionAnatomy,SemanticMotionEvent,SpatialGeometry,SpatialMotionPlan,TopologyState} from '../../animation/src/spatial-motion';

const point=(x:number,y:number):GeometryPoint=>({x,y});
const phraseAt=(scene:Scene,at:number)=>{const spoken=scene.retentionExecution?.beats.find(beat=>at>=beat.start/(scene.endSeconds-scene.startSeconds)&&at<=beat.end/(scene.endSeconds-scene.startSeconds))?.semantic_event??scene.purpose;return spoken.trim().slice(0,120);};
const topologyFor=(plan:ProcessPlan):TopologyState=>{
  const ids=plan.objects.map(object=>object.id),relationships=plan.relationships.map(item=>item.id);const regions=[] as TopologyState['regions'];
  if(plan.grammar==='FILTER_CLASSIFY')regions.push({id:'mixed-field',type:'FIELD',semantic_role:'MIXED_INPUT',members:ids.slice(0,1)},{id:'verified-region',type:'REGION',semantic_role:'VERIFIED',members:['fact']},{id:'provisional-region',type:'REGION',semantic_role:'PROVISIONAL',members:['inference']},{id:'unknown-region',type:'REGION',semantic_role:'UNKNOWN',members:['unknown']},{id:'verification-gate',type:'GATE',semantic_role:'FILTER_AND_VERIFY',members:['gate']});
  else if(plan.grammar==='HYPOTHESIS_BRANCHING')regions.push({id:'reasoning-field',type:'FIELD',semantic_role:'ACTIVE_REASONING_FIELD',members:ids},{id:'rejected-field',type:'OUTSIDE_FIELD',semantic_role:'REJECTED',members:[]});
  else if(plan.grammar==='EVIDENCE_PROOF')regions.push({id:'source-viewport',type:'SOURCE_VIEWPORT',semantic_role:'REAL_SOURCE',members:ids});
  else if(plan.grammar==='CONVERGENCE_PAYOFF'||plan.grammar==='TRANSFORMATION_STATE_CHANGE')regions.push({id:'unresolved-field',type:'FIELD',semantic_role:'UNRESOLVED',members:ids.slice(0,-1)},{id:'resolution-target',type:'CONVERGENCE_TARGET',semantic_role:'DEFENSIBLE_CONCLUSION',members:ids.slice(-1)});
  else regions.push({id:'active-field',type:'FIELD',semantic_role:'ACTIVE_REASONING_FIELD',members:ids});
  return {active_objects:ids,active_relationships:relationships,regions,paths:plan.relationships.map(item=>({id:item.id,from:item.from,to:item.to,semantic_role:item.type,state:item.state==='BROKEN'?'BROKEN':item.state==='REJECTED'?'REJECTED':item.state==='CONFIRMED'?'VERIFIED':'POSSIBLE'})),gaps:plan.events.some(event=>event.type==='BREAK')?['missing-evidence-gap']:[],anchors:plan.objects.filter(object=>object.state==='VERIFIED'||object.type==='EVIDENCE'||object.type==='PRINCIPLE').map(object=>object.id),focal_object:plan.objects[0]?.id??'none'};
};
const geometryFor=(plan:ProcessPlan,topology:TopologyState):SpatialGeometry=>{const positions:Record<string,GeometryPoint>={};const ids=topology.active_objects;
  if(plan.grammar==='HYPOTHESIS_BRANCHING'){positions[ids[0]??'origin']=point(.18,.46);ids.slice(1).forEach((id,index)=>positions[id]=point(.72,.25+index*.23));}
  else if(plan.grammar==='FILTER_CLASSIFY'){positions.raw=point(.14,.45);positions.gate=point(.46,.45);positions.fact=point(.78,.24);positions.inference=point(.78,.47);positions.unknown=point(.78,.7);}
  else if(plan.grammar==='EVIDENCE_PROOF')ids.forEach((id,index)=>positions[id]=point(.5,.2+index*.2));
  else if(plan.grammar==='CAUSAL_RELATIONSHIP'){positions[ids[0]??'a']=point(.2,.38);positions[ids[1]??'b']=point(.8,.38);positions[ids[2]??'gap']=point(.5,.55);positions[ids[3]??'variable']=point(.5,.76);}
  else ids.forEach((id,index)=>positions[id]=point(index%2?.78:.22,index<2?.3:.68));
  return {object_positions:positions,region_bounds:Object.fromEntries(topology.regions.map((region,index)=>[region.id,{x:.06+(index%2)*.48,y:.16+Math.floor(index/2)*.32,width:.4,height:.26}])),safe_zone:{top:.08,right:.06,bottom:.13,left:.06},caption_zone:{top:.76,bottom:.9},silhouette:plan.grammar==='HYPOTHESIS_BRANCHING'?'WIDE_BRANCH':plan.grammar==='FILTER_CLASSIFY'?'VERTICAL_FLOW':plan.grammar==='EVIDENCE_PROOF'?'FULL_SOURCE_VIEWPORT':plan.grammar==='CAUSAL_RELATIONSHIP'?'SPLIT_FIELD':plan.retention_role==='PAYOFF'?'CONVERGENCE':'CENTRAL_CLUSTER'};
};
const anatomyFor=(plan:ProcessPlan):MotionAnatomy=>({entry_pattern:plan.retention_role==='HOOK'?'INTERRUPT_FROM_OPPOSED_EDGES':plan.grammar==='EVIDENCE_PROOF'?'SOURCE_ESTABLISH':'SEQUENTIAL_OBJECT_ENTRY',trajectory_pattern:plan.grammar==='HYPOTHESIS_BRANCHING'?'ORIGIN_TO_DIVERGENT_PATHS':plan.grammar==='FILTER_CLASSIFY'?'INPUT_THROUGH_GATE_TO_REGIONS':plan.grammar==='CAUSAL_RELATIONSHIP'?'CONNECTED_TO_SEPARATED_FIELDS':plan.grammar==='EVIDENCE_PROOF'?'REGION_TO_REGION_VIEWPORT_TRAVEL':'MULTIPLE_PATHS_TO_RESOLUTION_TARGET',interaction_pattern:plan.events.map(event=>event.type).join('>'),settle_pattern:plan.retention_role==='PAYOFF'?'SIMPLIFIED_RESOLVED_ANCHOR':plan.grammar==='EVIDENCE_PROOF'?'FOCUS_THEN_EXIT':'READABLE_TOPOLOGY_STATE'});
const structural=(type:string)=>['BREAK','BRANCH','FILTER','SPLIT','MERGE','RESOLVE','SOURCE_PAN','EVIDENCE_TRACE'].includes(type);
const trajectoryFor=(event:ProcessEvent,plan:ProcessPlan)=>({origin:event.from_state,path_intent:event.type==='BRANCH'?'DIVERGE':event.type==='REJECT'||event.type==='COLLAPSE'?'LEAVE_ACTIVE_FIELD':event.type==='FILTER'?'PASS_THROUGH_GATE':event.type==='VERIFY'?'MOVE_TO_STABLE_ANCHOR':event.type==='BREAK'?'SEPARATE_AND_OPEN_GAP':event.type==='SOURCE_PAN'?'TRAVEL_TO_SEMANTIC_REGION':event.type==='MERGE'?'PRESERVE_IDENTITIES_UNTIL_NEW_WHOLE':event.type==='RESOLVE'?'CLOSE_UNRESOLVED_RELATIONSHIP':'REVEAL_STATE_CHANGE',interaction:event.semantic_reason,destination:event.to_state,settle_state:`${event.targets.join('+')} visibly ${event.to_state.toLowerCase()}`});
const cameraFor=(plan:ProcessPlan,scene:Scene):EvidenceCameraPlan|undefined=>plan.evidence?{source_asset_id:plan.evidence.asset_id,establish:{viewport:'FULL_SOURCE_WITH_IDENTITY',purpose:'Establish source identity and context before crop.',context_visibility:plan.evidence.viewport.context_visibility},moves:plan.evidence.regions.map((region,index)=>({from:index?plan.evidence!.regions[index-1]!.region_id:'SOURCE_ESTABLISH',to:region.region_id,spoken_anchor:{phrase:phraseAt(scene,.2+index*.25),event:`focus-${region.region_id}`,relation:'ON',at_seconds:Number(((scene.endSeconds-scene.startSeconds)*(.2+index*.25)).toFixed(3))},semantic_reason:region.viewer_should_notice,focus_action:index===0?'BRACKET':index===1?'VIEWPORT_CHANGE':'POINTER',settle_duration:index===2?.7:.55})),exit:{payload_complete_at:plan.evidence.payload_complete_event,next_semantic_state:'EXIT_TO_IMPLICATION'}}:undefined;

export const compileSpatialMotionPlan=(scene:Scene,renderMode:'PRODUCTION'|'DIAGNOSTIC'='PRODUCTION'):SpatialMotionPlan=>{const plan=scene.representationPlan;if(!plan)throw new Error(`REPRESENTATION_CAPABILITY_MISSING: ${scene.id}`);const topology=topologyFor(plan),geometry=geometryFor(plan,topology);const duration=scene.endSeconds-scene.startSeconds;const events:SemanticMotionEvent[]=plan.events.map((event,index)=>({event_id:event.id,event_type:event.type,at:event.at,role:plan.retention_role,intended_realization:{topology_delta:structural(event.type)?`${event.type} mutates active topology`:'Topology membership/state becomes visible',spatial_delta:structural(event.type)?'STRUCTURAL':'LOCAL',silhouette_delta:structural(event.type)?`${geometry.silhouette} changes ownership`:'Focal silhouette changes locally',relationship_delta:plan.relationships.length?`${event.targets.join(',')} relationship becomes ${event.to_state}`:'Object membership/state changes',focal_hierarchy_delta:`${event.targets[0]??topology.focal_object} becomes primary`,object_state_delta:`${event.from_state} → ${event.to_state}`,viewer_should_notice:event.perceptual_target.viewer_should_notice},trajectory:trajectoryFor(event,plan),motion_causality:{trigger:index?plan.events[index-1]!.id:'scene/voice entry',primary_event:event.id,resulting_events:plan.events[index+1]?[plan.events[index+1]!.id]:[]},spoken_anchor:{phrase:phraseAt(scene,event.at),event:event.id,relation:'ON',at_seconds:Number((duration*event.at).toFixed(3))},settle:{duration_seconds:event.type==='RESOLVE'?.8:.45,comprehension_seconds:event.type==='RESOLVE'||event.type==='LIMITATION_MARK'?.65:.35},idle_motion:false}));return {version:1,scene_id:scene.id,render_mode:renderMode,topology,geometry,events,focal_hierarchy:{primary:topology.focal_object,secondary:topology.active_objects.filter(id=>id!==topology.focal_object).slice(0,2),suppressed:topology.active_objects.slice(3)},dominant_visual_question:plan.retention_role==='HOOK'?'Are these actually connected?':plan.grammar==='HYPOTHESIS_BRANCHING'?'Which hypothesis survives?':plan.grammar==='EVIDENCE_PROOF'?'What does the evidence support and limit?':plan.retention_role==='PAYOFF'?'How does the unresolved relation become defensible?':'What state changes here?',density:{object_count:plan.objects.length,relationship_count:plan.relationships.length,simultaneous_labels:plan.display_copy.simultaneous_labels,occupied_area:Math.min(.84,.18*plan.objects.length)},motion_anatomy:anatomyFor(plan),camera_plan:cameraFor(plan,scene),repair:{pass:0,displacement_multiplier:1,topology_emphasis:1,settle_multiplier:1,camera_travel_multiplier:1,diagnosis:[]},compile_failures:events.some(event=>event.intended_realization.spatial_delta!=='MICRO'&&!event.trajectory.destination)?['SEMANTIC_MOTION_PLAN_INCOMPLETE']:[]};};
export const compileSpatialMotionPlans=(manifest:AnimationManifest,renderMode:'PRODUCTION'|'DIAGNOSTIC'='PRODUCTION')=>{for(const scene of manifest.scenes)if(scene.representationPlan)scene.representationPlan.spatial_motion=compileSpatialMotionPlan(scene,renderMode);return manifest;};

export const diagnoseFailureOrigin=(failure:string):FailureOrigin=>failure==='REPRESENTATION_CAPABILITY_MISSING'?'CAPABILITY':/PLAN_|SEMANTIC_MOTION_PLAN_INCOMPLETE/.test(failure)?'PLAN':/TIMING|SETTLE|COMPREHENSION|OUT_OF_SYNC/.test(failure)?'TIMING':/EVIDENCE_|SOURCE_VIEWPORT/.test(failure)?'EVIDENCE_CAMERA':/REUSE|CENTERED/.test(failure)?'WHOLE_VIDEO_REPETITION':/MISMATCH/.test(failure)?'QA_MISMATCH':'REALIZATION';
export const repairSpatialMotion=(manifest:AnimationManifest,failures:Array<{scene_id:string;failure_class:string}>):AnimationManifest=>{const copy=JSON.parse(JSON.stringify(manifest)) as AnimationManifest;for(const scene of copy.scenes){const plan=scene.representationPlan?.spatial_motion;if(!plan)continue;const own=failures.filter(item=>item.scene_id===scene.id&&['REALIZATION','TIMING','EVIDENCE_CAMERA','WHOLE_VIDEO_REPETITION'].includes(diagnoseFailureOrigin(item.failure_class)));if(!own.length)continue;if(plan.repair.pass>=1)throw new Error(`REALIZATION_REPAIR_LIMIT_EXCEEDED: ${scene.id}`);plan.repair={pass:1,displacement_multiplier:1.55,topology_emphasis:1.45,settle_multiplier:1.28,camera_travel_multiplier:1.5,diagnosis:[...new Set(own.map(item=>item.failure_class))]};for(const event of plan.events){event.settle.duration_seconds*=plan.repair.settle_multiplier;event.settle.comprehension_seconds*=plan.repair.settle_multiplier;}}return copy;};
