import {mkdirSync,readFileSync,renameSync,writeFileSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import type {AnimationManifest} from '../../animation/src/model';
import type {VoicePlan} from '../../voice/src/model';
import {analyzeActualRetentionV2,evaluateCreativeContinuity} from '../src/retention-v2';

const atomicJson=(path:string,value:unknown)=>{mkdirSync(dirname(path),{recursive:true});const temporary=`${path}.${process.pid}.tmp`;writeFileSync(temporary,`${JSON.stringify(value,null,2)}\n`,'utf8');renameSync(temporary,path);};
const json=<T>(path:string)=>JSON.parse(readFileSync(resolve(path),'utf8')) as T;
const oldVideo=resolve('generated/regression/retention/CKAI-0004-phase1G-human-rejected.mp4');const oldAnimation=json<AnimationManifest>('generated/regression/retention/CKAI-0004-phase1G-animation.json');const oldVoice=json<VoicePlan>('generated/regression/retention/CKAI-0004-phase1G-voice.json');
const newVideo=resolve(process.argv[2]??'generated/probes/phase1h/CKAI-0004-phase1h-local-probe.mp4');const newAnimation=json<AnimationManifest>(process.argv[3]??'generated/probes/phase1h/animation.json');const newVoice=json<VoicePlan>(process.argv[4]??'generated/probes/phase1h/voice.json');
const oldTimeline=analyzeActualRetentionV2(oldVideo,oldAnimation,oldVoice);const oldContinuity=evaluateCreativeContinuity(oldAnimation,oldTimeline);const newTimeline=analyzeActualRetentionV2(newVideo,newAnimation,newVoice);const newContinuity=evaluateCreativeContinuity(newAnimation,newTimeline);
atomicJson(resolve('generated/regression/retention/actual-retention-timeline.json'),oldTimeline);atomicJson(resolve('generated/regression/retention/creative-continuity-qa.json'),oldContinuity);
const summarize=(timeline:typeof oldTimeline,continuity:typeof oldContinuity,manifest:AnimationManifest)=>({duration_seconds:timeline.duration_seconds,long_silence_spans_over_1_5s:timeline.high_risk_silence_count,silence_dead_zone_candidates_over_2s:timeline.over_two_second_silence_count,high_risk_scene_tails:timeline.scenes.filter((scene)=>scene.scene_tail_risk==='HIGH'||scene.scene_tail_risk==='FAIL').length,planned_beats:timeline.scenes.reduce((sum,scene)=>sum+scene.planned_beats,0),executed_beats:timeline.scenes.reduce((sum,scene)=>sum+scene.executed_beats,0),longest_weak_progression_window:timeline.longest_weak_progression_window,legacy_visual_behavior_detections:timeline.scenes.filter((scene)=>scene.legacy_visual_behavior).length,code_native_semantic_mechanism_coverage:`${manifest.scenes.filter((scene)=>scene.hybridSource?.choice==='CODE_NATIVE'&&scene.semanticMechanism).length}/${manifest.scenes.filter((scene)=>scene.hybridSource?.choice==='CODE_NATIVE').length}`,mid_video_retention_collapse:continuity.mid_video_retention_collapse,whole_video_machine_verdict:timeline.verdict==='PASS'&&continuity.verdict==='PASS'?'PASS':'FAIL'});
const comparison={old_binary:{path:oldVideo,...summarize(oldTimeline,oldContinuity,oldAnimation)},new_binary:{path:newVideo,...summarize(newTimeline,newContinuity,newAnimation)}};atomicJson(resolve('generated/probes/phase1h/before-after.json'),comparison);process.stdout.write(`${JSON.stringify(comparison,null,2)}\n`);
