import {copyFileSync,mkdirSync,readFileSync,renameSync,writeFileSync} from 'node:fs';
import {dirname,join,relative,resolve} from 'node:path';
import type {AnimationManifest} from '../../animation/src/model';
import type {PerceptualProgressionQa} from '../src/perceptual-qa';
import {evaluateMotionSpatialQa} from '../src/motion-spatial-qa';
import {selectBestCandidate,type CandidateScore} from '../src/representation';

const root=resolve('.'),out=resolve('generated/probes/phase1j');
const rel=(path:string)=>relative(root,path).replaceAll('\\','/');
const atomicJson=(path:string,value:unknown)=>{mkdirSync(dirname(path),{recursive:true});const temp=`${path}.tmp-${process.pid}`;writeFileSync(temp,`${JSON.stringify(value,null,2)}\n`);renameSync(temp,path);};
const unique=<T>(values:T[])=>[...new Set(values)];
const candidates=['R0','R0-R'].map(label=>{const dir=join(out,label.toLowerCase()),props=JSON.parse(readFileSync(join(dir,'props.json'),'utf8')) as {manifest:AnimationManifest},qa=JSON.parse(readFileSync(join(dir,'qa-summary.json'),'utf8')) as any,perceptual=JSON.parse(readFileSync(join(dir,'perceptual-qa.json'),'utf8')) as PerceptualProgressionQa;const motionSpatial=evaluateMotionSpatialQa(props.manifest,perceptual);const hard=unique([...qa.retention.failure_classes,...qa.perceptual.failure_classes,...qa.representation.failures,...motionSpatial.failures,...qa.continuity.failure_classes,...qa.structuralFailures,...qa.sourceErrors]);const candidate:CandidateScore={...qa.candidate,production_cleanliness:motionSpatial.production_cleanliness==='PASS',hard_failures:hard.length,motion_spatial_failures:motionSpatial.failures.length};const updated={...qa,productionCleanliness:candidate.production_cleanliness,motionSpatial,candidate};atomicJson(join(dir,'motion-spatial-actual-qa.json'),motionSpatial);atomicJson(join(dir,'qa-summary.json'),updated);return {label,dir,manifest:props.manifest,qa:updated,candidate};});
const selected=selectBestCandidate(candidates.map(item=>item.candidate)),selectedResult=candidates.find(item=>item.label===selected.candidate_label)!;atomicJson(join(out,'candidate-comparison.json'),{candidates:candidates.map(item=>item.candidate),selected,policy:['Meaning Gate','Evidence Integrity','Production Cleanliness','Hard Retention / Perceptual','Motion / Spatial Realization','Creative Quality','Cost / Polish']});const finalVideo=join(out,'CKAI-0004-phase1j-selected.mp4'),reviewDir=join(out,'review-package'),reviewVideo=join(reviewDir,'CKAI-0004_phase1j_visual-review.mp4');copyFileSync(resolve(selected.video),finalVideo);mkdirSync(reviewDir,{recursive:true});copyFileSync(finalVideo,reviewVideo);const machinePass=selectedResult.qa.meaningPass&&selectedResult.qa.evidencePass&&selectedResult.qa.productionCleanliness&&selectedResult.qa.retention.verdict==='PASS'&&selectedResult.qa.perceptual.verdict==='PASS'&&selectedResult.qa.representation.verdict==='PASS'&&selectedResult.qa.motionSpatial.verdict==='PASS'&&selectedResult.qa.continuity.verdict==='PASS';atomicJson(join(out,'selected-actual-qa.json'),selectedResult.qa);atomicJson(join(out,'realization-repair-result.json'),{repair_passes_used:1,candidates:candidates.map(item=>({label:item.label,repair_pass:item.candidate.repair_pass,diagnoses:item.qa.motionSpatial.scenes.flatMap((scene:any)=>scene.origins.map((origin:any)=>({scene_id:scene.scene_id,...origin})))})),selected:selected.candidate_label,recomputed_from_cached_actual_vision:true});atomicJson(join(reviewDir,'package-manifest.json'),{contentId:'CKAI-0004',packageState:'PHASE1J_PRODUCTION_VISUAL_REVIEW_PACKAGE',renderMode:'PRODUCTION',selectedCandidate:selected.candidate_label,selectionBasis:selected,machineAcceptance:machinePass?'PASS':'NOT_YET_PASS',humanProductOwnerAcceptance:'PENDING',releaseState:'PENDING_RELEASE_APPROVAL',video:rel(reviewVideo),videoSource:selected.video,motionSpatialQa:rel(join(selectedResult.dir,'motion-spatial-actual-qa.json')),note:'Best production candidate only; no Release Approval.'});if(!machinePass)atomicJson(join(out,'needs-chatgpt-creative-review.json'),{content_id:'CKAI-0004',status:'NEEDS_CHATGPT_CREATIVE_REVIEW',selected_candidate:selected.candidate_label,repair_passes_used:1,creative_replan_rounds_used:0,remaining_failures:selectedResult.qa.motionSpatial.scenes.filter((scene:any)=>scene.failures.length).map((scene:any)=>({scene_id:scene.scene_id,failures:scene.failures,origins:scene.origins})),recommended_review:'Review remaining actual-pixel motion/spatial failures; preserve meaning, evidence and production cleanliness.'});console.log(JSON.stringify({selected:selected.candidate_label,machine_acceptance:machinePass?'PASS':'NOT_YET_PASS',reused_vision_calls:12,new_vision_calls:0},null,2));
