import {devNull} from 'node:os';
import {existsSync,mkdirSync,readFileSync,readdirSync,renameSync,writeFileSync} from 'node:fs';
import {dirname,join,relative,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {parseFrontmatter} from '../../animation/src/engine/upstream';
import {runTechnicalQa} from '../../animation/src/engine/qa';
import type {AnimationManifest} from '../../animation/src/model';
import {probeAudioLevels} from '../../voice/src/media';
import type {VoicePlan} from '../../voice/src/model';
import {runVoiceQa} from '../../voice/src/qa';
import {sha256} from '../../voice/src/segment';
import {inspectActualBinaryExperience} from '../src/experience';
import {CKAI_SHORT_FORM_MASTERING_V1,evaluateMasteringQa,masterReviewBinary,masterVoiceTimeline} from '../src/mastering';
import {createGenericReviewDraft} from '../src/manifest/generic';
import {probeVideo} from '../src/media';
import type {FinalReviewManifest,FinishingAudioAsset,SfxCueType,SourceReference} from '../src/model';
import {runReviewQa} from '../src/qa';
import {measureRuntimeRetention} from '../src/retention';
import {bindSfxToSemanticEvents} from '../src/semantic-audio';

const root=process.cwd();const contentId='CKAI-0004';const reviewVersion=process.argv[2]??'v5';if(!/^v\d+(?:\.\d+)?$/.test(reviewVersion))throw new Error('Review version must use vN or vN.N');
const bundledMediaDirectory=resolve('node_modules/@remotion/compositor-win32-x64-msvc');
if(process.platform==='win32'&&existsSync(resolve(bundledMediaDirectory,'ffprobe.exe'))){
  const capcutApps=resolve(process.env.LOCALAPPDATA??'','CapCut/Apps');
  const qaMediaDirectory=existsSync(capcutApps)?readdirSync(capcutApps).sort((a,b)=>b.localeCompare(a,undefined,{numeric:true})).map((version)=>resolve(capcutApps,version)).find((directory)=>existsSync(resolve(directory,'ffmpeg.exe'))):undefined;
  process.env.Path=`${qaMediaDirectory?`${qaMediaDirectory};`:''}${bundledMediaDirectory};${process.env.Path??''}`;
}
const acceptedAnimationSha='8848D754849B7F554234B0BC65F776720C96C3C9064F3D72B6C4BB557039AA1D';
const acceptedVoiceSha='EE7464C79A30A41EFC5EA84717958FC23F4F7E960F9711CF2BB623318A580BFF';
const acceptedVoicePreviewSha='7D18BDF30E2AF179CF4C4B56A9E8E25E8581DF187A35956673300E1D3731A9A2';
const rel=(path:string)=>relative(root,path).replaceAll('\\','/');const ownerRel=(owner:string,path:string)=>relative(dirname(owner),path).replaceAll('\\','/');const hash=(path:string)=>sha256(readFileSync(path));
const atomicWrite=(path:string,value:string)=>{mkdirSync(dirname(path),{recursive:true});const temporary=`${path}.${process.pid}.tmp`;writeFileSync(temporary,value,'utf8');renameSync(temporary,path);};const atomicJson=(path:string,value:unknown)=>atomicWrite(path,`${JSON.stringify(value,null,2)}\n`);
const run=(command:string,args:string[],code:string)=>{const result=spawnSync(command,args,{cwd:root,encoding:'utf8',timeout:600_000});if(result.status!==0)throw new Error(`${code}: ${(result.stderr||result.stdout).slice(-3000)}`);return result;};
const probeWindowLevels=(path:string,startSeconds:number,durationSeconds:number,side=false,midrange=false)=>{const filters=[side?'pan=mono|c0=c0-c1':'',midrange?'highpass=f=250,lowpass=f=5000':'','volumedetect'].filter(Boolean).join(',');const result=run('ffmpeg',['-hide_banner','-nostats','-ss',String(startSeconds),'-t',String(durationSeconds),'-i',path,'-af',filters,'-f','null',devNull],'AUDIO_WINDOW_QA_FAILED');const mean=result.stderr.match(/mean_volume:\s*(-?\d+(?:\.\d+)?) dB/);const peak=result.stderr.match(/max_volume:\s*(-?\d+(?:\.\d+)?) dB/);if(!mean||!peak)throw new Error(`No loudness result for ${rel(path)}`);return{meanVolumeDb:Number(mean[1]),maxVolumeDb:Number(peak[1])};};

const animationSnapshotPath=resolve('generated/production/CKAI-0004/v5/animation-manifest.pending.json');const animationArtifactPath=resolve('content/animations/CKAI-0004_tach-du-kien-suy-luan-chua-biet_animation-v5.md');
const voiceSnapshotPath=resolve('generated/voice/CKAI-0004/v5/voice-plan.pending.json');const voiceArtifactPath=resolve('content/voices/CKAI-0004_tach-du-kien-suy-luan-chua-biet_voice-plan-v5.md');const voicePreviewPath=resolve('generated/previews/CKAI-0004-voice-v5.mp4');
const audioPlanPath=resolve('generated/audio/CKAI-0004/v4/audio-experience-plan.json');const mixOverridePath=resolve(`generated/audio/CKAI-0004/${reviewVersion}/mix-override.json`);const masteringConfigPath=resolve(`generated/audio/CKAI-0004/${reviewVersion}/mastering.json`);const masteringEnabled=existsSync(masteringConfigPath);const registryPath=resolve('generated/audio/ckai-original/library.generated.json');
for(const path of [animationSnapshotPath,animationArtifactPath,voiceSnapshotPath,voiceArtifactPath,voicePreviewPath,audioPlanPath,registryPath])if(!existsSync(path))throw new Error(`Required canonical source missing: ${rel(path)}`);
if(hash(animationSnapshotPath)!==acceptedAnimationSha||hash(voiceSnapshotPath)!==acceptedVoiceSha||hash(voicePreviewPath)!==acceptedVoicePreviewSha)throw new Error('Accepted STEP 05/06 source hash is stale');

const animationFields=parseFrontmatter(readFileSync(animationArtifactPath,'utf8'));if(animationFields.animation_review!=='pass'||animationFields.human_decision!=='approved'||animationFields.voice_handoff_status!=='READY'||animationFields.operator_acceptance_by!=='chatgpt-work'||String(animationFields.operator_acceptance_source_sha256??'').toUpperCase()!==acceptedAnimationSha)throw new Error('Canonical STEP 05 acceptance is invalid');
const animation=JSON.parse(readFileSync(animationSnapshotPath,'utf8')) as AnimationManifest;animation.technicalQa='PASS';animation.animationReview='pass';animation.humanDecision='approved';animation.unresolvedBlockers=[];animation.voiceHandoffStatus='READY';const animationQa=runTechnicalQa(animation,false);if(!animationQa.pass)throw new Error(`STEP05_QA_BLOCKED:\n${animationQa.errors.join('\n')}`);

const voiceFields=parseFrontmatter(readFileSync(voiceArtifactPath,'utf8'));const expectedVoice:Record<string,string>={voice_review:'pass',human_decision:'approved',final_review_input_status:'READY',operator_acceptance_by:'chatgpt-work'};for(const [field,value] of Object.entries(expectedVoice))if(voiceFields[field]!==value)throw new Error(`Canonical STEP 06 acceptance requires ${field}=${value}`);if(String(voiceFields.operator_acceptance_source_sha256??'').toUpperCase()!==acceptedVoiceSha||!Number.isFinite(Date.parse(String(voiceFields.operator_acceptance_at??'')))||!String(voiceFields.operator_acceptance_basis??'').toUpperCase().includes(acceptedVoicePreviewSha))throw new Error('Canonical STEP 06 acceptance provenance/hash is invalid');
const technicalVoice=JSON.parse(readFileSync(voiceSnapshotPath,'utf8')) as VoicePlan;technicalVoice.finalReviewInputStatus='BLOCKED';delete technicalVoice.finalReviewExportHandoffStatus;const voicePlan:VoicePlan={...technicalVoice,voiceReview:'pass',humanDecision:'approved',finalReviewInputStatus:'READY',unresolvedBlockers:[]};const voiceQa=runVoiceQa({plan:voicePlan,animation},'production',true,true);if(!voiceQa.pass)throw new Error(`VOICE_QA_BLOCKED:\n${voiceQa.errors.join('\n')}`);
const canonicalVoiceAudioPath=resolve(voicePlan.assembledAudioPath);const reviewVoiceAudioPath=masteringEnabled?resolve(`generated/audio/CKAI-0004/${reviewVersion}/voice-mastered.wav`):canonicalVoiceAudioPath;if(masteringEnabled)masterVoiceTimeline(canonicalVoiceAudioPath,reviewVoiceAudioPath);

const audioPlan=JSON.parse(readFileSync(audioPlanPath,'utf8')) as any;if(existsSync(mixOverridePath)){const override=JSON.parse(readFileSync(mixOverridePath,'utf8')) as{policyId:string;musicAssetId:string;baseGainDb:number;duckUnderVoiceDb:number;fadeInSeconds:number;fadeOutSeconds:number};if(override.policyId!=='CKAI_AUDIO_EXPERIENCE_V1'||override.musicAssetId!==audioPlan.music.selectedAsset.id)throw new Error('Mix override is not bound to the approved Audio Experience policy and music asset');audioPlan.music.plannedBaseGainDb=override.baseGainDb;audioPlan.music.plannedDuckUnderVoiceDb=override.duckUnderVoiceDb;audioPlan.music.plannedFadeInSeconds=override.fadeInSeconds;audioPlan.music.plannedFadeOutSeconds=override.fadeOutSeconds;}if(masteringEnabled){const config=JSON.parse(readFileSync(masteringConfigPath,'utf8')) as{policyId:string;humanAudioReview:string};if(config.policyId!==CKAI_SHORT_FORM_MASTERING_V1.id||config.humanAudioReview!=='REQUIRED')throw new Error('Mastering config is not bound to the canonical generic policy');audioPlan.music.plannedBaseGainDb=CKAI_SHORT_FORM_MASTERING_V1.music.baseGainDb;audioPlan.music.plannedDuckUnderVoiceDb=CKAI_SHORT_FORM_MASTERING_V1.music.duckUnderVoiceDb;audioPlan.music.plannedFadeInSeconds=CKAI_SHORT_FORM_MASTERING_V1.music.fadeInSeconds;audioPlan.music.plannedFadeOutSeconds=CKAI_SHORT_FORM_MASTERING_V1.music.fadeOutSeconds;}const registry=JSON.parse(readFileSync(registryPath,'utf8')) as{assets:Array<any>};const byId=new Map(registry.assets.map((asset)=>[asset.assetId,asset]));const musicDefinition=audioPlan.music.selectedAsset;const musicRegistry=byId.get(musicDefinition.id);if(!musicRegistry?.productionApproved||musicRegistry.sha256!==musicDefinition.sha256||hash(resolve(musicDefinition.localPath))!==musicDefinition.sha256)throw new Error('Selected music is not bound to the approved local-audio registry');
const provenance='CKAI_ORIGINAL_AUDIO_FFMPEG_V1 deterministic synthesis; no external samples, downloads or providers';const baseAssets:FinishingAudioAsset[]=[{id:musicDefinition.id,type:'music',localPath:musicDefinition.localPath,source:'CKAI_PROCEDURAL_GENERATION',provenance,purpose:'continuous restrained editorial bed',licenseStatus:'approved',startSeconds:0,durationSeconds:animation.totalSeconds,gainDb:audioPlan.music.plannedBaseGainDb,fadeInSeconds:audioPlan.music.plannedFadeInSeconds,fadeOutSeconds:audioPlan.music.plannedFadeOutSeconds,duckUnderVoiceDb:audioPlan.music.plannedDuckUnderVoiceDb,required:true,sha256:musicDefinition.sha256}];
for(const cue of audioPlan.sfx.cuePlan.filter((value:any)=>value.use!=='none')){const registryAsset=byId.get(cue.use);if(!registryAsset?.productionApproved||hash(resolve(registryAsset.path))!==registryAsset.sha256)throw new Error(`${cue.use} is not production-approved or has stale bytes`);baseAssets.push({id:`${cue.use}-${cue.sceneId}`,type:'sfx',localPath:registryAsset.path,source:'CKAI_PROCEDURAL_GENERATION',provenance,purpose:cue.purpose,licenseStatus:'approved',sceneId:cue.sceneId,cueType:cue.cueType as SfxCueType,startSeconds:0,durationSeconds:registryAsset.durationSeconds,gainDb:cue.gainDb,required:true,sha256:registryAsset.sha256});}
const semantic=bindSfxToSemanticEvents(baseAssets.filter((asset)=>asset.type==='sfx'),animation);const assets=[baseAssets[0]!,...semantic.assets];

const one=(directory:string)=>{const matches=readdirSync(directory).filter((name)=>name.startsWith(`${contentId}_`)&&name.endsWith('.md'));if(matches.length!==1)throw new Error(`Exactly one canonical source required in ${rel(directory)}`);return join(directory,matches[0]!);};
const scriptPath=resolve(voicePlan.sourceScript);const storyboardPath=one(resolve('content/storyboards'));const visualPath=resolve(animation.sourceVisualDirection);const sourceChain=[['script',scriptPath],['storyboard',storyboardPath],['visual-direction',visualPath],['animation',animationArtifactPath],['voice',voiceArtifactPath]].map(([stage,path])=>({stage,path:rel(path),sha256:hash(path)})) as SourceReference[];
const review=createGenericReviewDraft({contentId,animation,voicePlan,sourceChain,sourceVoiceSnapshot:rel(voiceSnapshotPath),sourceVoiceSnapshotSha256:acceptedVoiceSha,sourceVoiceAudioSha256:hash(canonicalVoiceAudioPath),sourceVoicePreviewSha256:acceptedVoicePreviewSha});review.musicMode='local-approved';review.sfxMode='local-approved';review.finishingAudioAssets=assets;review.reviewPreview={path:`generated/previews/CKAI-0004-review-${reviewVersion}.mp4`,captionMode:'on',audioMixMode:'voice-plus-local'};
const retention=measureRuntimeRetention(voicePlan,animation);if(retention.retentionPolicyResult!=='PASS'||retention.excessiveRetentionPauses!==0)throw new Error('SHORT_FORM_RETENTION_POLICY_V1 blocked V5 before render');
const voiceWindows=voicePlan.segments.map((segment)=>({startSeconds:segment.slotStartSeconds,endSeconds:segment.slotStartSeconds+(segment.measuredDurationSeconds??segment.slotEndSeconds-segment.slotStartSeconds)}));const productionDirectory=resolve(`generated/production/CKAI-0004/${reviewVersion}`);const reviewDirectory=resolve(`generated/review/CKAI-0004/${reviewVersion}`);const propsPath=join(productionDirectory,'review-props.json');const reviewSnapshotPath=join(reviewDirectory,'final-review.pending.json');const reviewArtifactPath=resolve(`content/reviews/CKAI-0004_tach-du-kien-suy-luan-chua-biet_final-review-${reviewVersion}.md`);const outputPath=resolve(review.reviewPreview.path);const renderOutputPath=masteringEnabled?resolve(`generated/previews/CKAI-0004-review-${reviewVersion}-premaster.mp4`):outputPath;mkdirSync(reviewDirectory,{recursive:true});atomicJson(propsPath,{manifest:animation,audioPublicPath:relative(resolve('generated'),reviewVoiceAudioPath).replaceAll('\\','/'),captions:review.captions,stage:'review',finishingAudioAssets:assets,voiceWindows,semanticSfxBindings:semantic.bindings,masteringPolicyId:masteringEnabled?CKAI_SHORT_FORM_MASTERING_V1.id:null});
mkdirSync(dirname(outputPath),{recursive:true});const reuseCurrentPremaster=masteringEnabled&&process.argv.includes('--reuse-premaster')&&existsSync(renderOutputPath);if(!reuseCurrentPremaster)run(process.execPath,[resolve('node_modules/@remotion/cli/remotion-cli.js'),'render','video-factory/animation/src/index.ts','CKAI-Generic-Pipeline',renderOutputPath,`--props=${rel(propsPath)}`,'--public-dir=generated','--codec=h264','--concurrency=2'],'REMOTION_V5_REVIEW_FAILED');const masteringRecord=masteringEnabled?masterReviewBinary(renderOutputPath,outputPath):null;
const media=probeVideo(outputPath);review.reviewPreview={...review.reviewPreview,sha256:hash(outputPath),codec:media.videoCodec,audioCodec:media.audioCodec,width:media.width,height:media.height,fps:media.fps,durationSeconds:Number(media.durationSeconds.toFixed(6))};const reviewQa=runReviewQa({review,voicePlan,animation},'production',true);if(!reviewQa.pass)throw new Error(`FINAL_REVIEW_TECHNICAL_QA_BLOCKED:\n${reviewQa.errors.join('\n')}`);const experience=inspectActualBinaryExperience(outputPath);if(!experience.pass)throw new Error(`ACTUAL_BINARY_EXPERIENCE_BLOCKED:\n${experience.errors.join('\n')}`);
const ebur=run('ffmpeg',['-hide_banner','-nostats','-i',outputPath,'-filter_complex','ebur128=peak=true','-f','null',devNull],'EBUR128_FAILED').stderr;
const integratedMatch=[...ebur.matchAll(/I:\s*(-?\d+(?:\.\d+)?) LUFS/g)].at(-1);const truePeakMatch=[...ebur.matchAll(/Peak:\s*(-?\d+(?:\.\d+)?) dBFS/g)].at(-1);const lraMatch=[...ebur.matchAll(/LRA:\s*(-?\d+(?:\.\d+)?) LU/g)].at(-1);if(!integratedMatch||!truePeakMatch||!lraMatch)throw new Error('Actual-binary EBU R128 metrics unavailable');const integratedLufs=Number(integratedMatch[1]);const truePeakDbtp=Number(truePeakMatch[1]);const lra=Number(lraMatch[1]);
const voiceLevels=probeAudioLevels(masteringEnabled?reviewVoiceAudioPath:voicePreviewPath);if(!masteringEnabled&&(Math.abs(experience.meanVolumeDb-voiceLevels.meanVolumeDb)>3.1||Math.abs(experience.maxVolumeDb-voiceLevels.maxVolumeDb)>3.1))throw new Error('Voice-first mix diverges materially from accepted Voice loudness');
const musicMeanDuringVoiceDb=musicRegistry.meanVolumeDb+audioPlan.music.plannedBaseGainDb+audioPlan.music.plannedDuckUnderVoiceDb;const musicMeanDuringPausesDb=musicRegistry.meanVolumeDb+audioPlan.music.plannedBaseGainDb;const musicRelativeToVoiceDb=Number((musicMeanDuringVoiceDb-voiceLevels.meanVolumeDb).toFixed(1));
const interUnitGaps=voicePlan.segments.slice(0,-1).map((segment,index)=>{const start=segment.slotStartSeconds+(segment.measuredDurationSeconds??segment.slotEndSeconds-segment.slotStartSeconds);return{start,end:voicePlan.segments[index+1]!.slotStartSeconds};}).filter((gap)=>gap.end-gap.start>.4).sort((a,b)=>(b.end-b.start)-(a.end-a.start));const musicProbeGap=interUnitGaps.find((gap)=>semantic.bindings.every((binding)=>binding.semanticEventSeconds<gap.start||binding.semanticEventSeconds>gap.end))??interUnitGaps[0]!;const pauseStart=musicProbeGap.start+.1;const pauseDuration=Math.min(.9,musicProbeGap.end-musicProbeGap.start-.2);const musicPauseWindow=probeWindowLevels(outputPath,pauseStart,pauseDuration);const pauseSideWindow=probeWindowLevels(outputPath,pauseStart,pauseDuration,true);const pauseMidrangeWindow=probeWindowLevels(outputPath,pauseStart,pauseDuration,false,true);
const activeCandidates=voicePlan.segments.map((segment)=>({start:segment.slotStartSeconds+.25,end:segment.slotStartSeconds+(segment.measuredDurationSeconds??segment.slotEndSeconds-segment.slotStartSeconds)-.2})).filter((window)=>window.end-window.start>=.8);const activeProbe=activeCandidates.find((window)=>semantic.bindings.every((binding)=>binding.semanticEventSeconds<window.start-.2||binding.semanticEventSeconds>window.end+.2))??activeCandidates[0]!;const activeDuration=Math.min(1.2,activeProbe.end-activeProbe.start);const activeSpeechWindow=probeWindowLevels(outputPath,activeProbe.start,activeDuration);const activeSideWindow=probeWindowLevels(outputPath,activeProbe.start,activeDuration,true);const sideRecoveryDb=Number((pauseSideWindow.meanVolumeDb-activeSideWindow.meanVolumeDb).toFixed(1));
const sfxCues=semantic.bindings.map((binding)=>{const asset=assets.find((item)=>item.id===binding.assetId)!;const registryAsset=byId.get(asset.id.replace(/-SC-\d+$/,''));const actual=probeWindowLevels(outputPath,binding.semanticEventSeconds,Math.min(asset.durationSeconds??1,1.5));return{...binding,effectiveSfxPeakDb:Number((registryAsset.maxVolumeDb+asset.gainDb).toFixed(1)),actualBinaryWindowMeanDb:actual.meanVolumeDb,actualBinaryWindowPeakDb:actual.maxVolumeDb};});const sfxAudible=sfxCues.every((cue)=>cue.effectiveSfxPeakDb>-35&&cue.actualBinaryWindowPeakDb>-20);
const relationshipMinimum=masteringEnabled?-CKAI_SHORT_FORM_MASTERING_V1.music.maximumBelowVoiceDb:-22;const relationshipMaximum=masteringEnabled?-CKAI_SHORT_FORM_MASTERING_V1.music.minimumBelowVoiceDb:-18;const pauseFloor=masteringEnabled?CKAI_SHORT_FORM_MASTERING_V1.qa.minimumPauseMusicMeanDb:-55;const musicAudible=musicMeanDuringVoiceDb>-65&&musicMeanDuringPausesDb>-60&&musicPauseWindow.meanVolumeDb>=pauseFloor;const musicActuallyAudible=musicAudible&&musicRelativeToVoiceDb>=relationshipMinimum&&musicRelativeToVoiceDb<=relationshipMaximum;const clippingResult=experience.maxVolumeDb<=0&&truePeakDbtp<=(masteringEnabled?CKAI_SHORT_FORM_MASTERING_V1.truePeakMaximumDbtp:.1)?'PASS':'FAIL';
const masteringQa=masteringEnabled?evaluateMasteringQa({integratedLufs,truePeakDbtp,meanVolumeDb:experience.meanVolumeDb,maxVolumeDb:experience.maxVolumeDb,lra,activeSpeechMeanDb:activeSpeechWindow.meanVolumeDb,pauseMusicMeanDb:musicPauseWindow.meanVolumeDb,integratedGainDb:Number((integratedLufs-masteringRecord!.firstPass.inputIntegratedLufs).toFixed(1)),clipping:clippingResult!=='PASS',musicMidrangeUsable:pauseMidrangeWindow.meanVolumeDb>=-55,musicDoesNotMaskVoice:activeSpeechWindow.meanVolumeDb-musicPauseWindow.meanVolumeDb>=CKAI_SHORT_FORM_MASTERING_V1.qa.minimumSpeechToPauseMeanDb&&musicRelativeToVoiceDb<=relationshipMaximum,duckingPerceptuallySmooth:sideRecoveryDb>=2,sfxPerceptuallyPresent:sfxAudible}):null;
if(!musicActuallyAudible||!sfxAudible||clippingResult!=='PASS'||masteringQa?.status==='BLOCKED')throw new Error(`Actual ${reviewVersion} finishing/mastering QA blocked: ${JSON.stringify({musicActuallyAudible,sfxAudible,clippingResult,masteringQa})}`);
if(masteringEnabled)(review as any).masteringQa={policyId:CKAI_SHORT_FORM_MASTERING_V1.id,status:'PASS',humanAudioReview:'REQUIRED',actualBinarySha256:review.reviewPreview.sha256};
const metrics={status:'PASS',reviewVersion,path:review.reviewPreview.path,sha256:review.reviewPreview.sha256,durationSeconds:review.reviewPreview.durationSeconds,retention,spokenCopyIntegrity:voicePlan.segments.every((segment,index)=>segment.originalText===animation.voiceHandoff.sceneSlots[index]?.spokenCopy)?'PASS':'FAIL',audioCodec:experience.audioCodec,sampleRate:experience.audioSampleRate,channels:experience.audioChannels,meanVolumeDb:experience.meanVolumeDb,maxVolumeDb:experience.maxVolumeDb,integratedLufs,truePeakDbtp,lra,longestSilenceSeconds:experience.longestSilenceSeconds,clippingResult,mastering:masteringRecord?{...masteringRecord,derivedVoice:{sourcePath:rel(canonicalVoiceAudioPath),sourceSha256:hash(canonicalVoiceAudioPath),path:rel(reviewVoiceAudioPath),sha256:hash(reviewVoiceAudioPath)},qa:masteringQa,humanAudioReviewRequired:true,activeSpeechWindow:{startSeconds:activeProbe.start,durationSeconds:activeDuration,...activeSpeechWindow},activeSideWindow,pauseSideWindow,pauseMidrangeWindow,sideRecoveryDb}:null,music:{audible:musicAudible,musicActuallyAudible:musicActuallyAudible?'PASS':'FAIL',renderedMeanDuringVoiceDb:Number(musicMeanDuringVoiceDb.toFixed(1)),renderedMeanDuringPausesDb:Number(musicMeanDuringPausesDb.toFixed(1)),relativeToVoiceMeanDb:musicRelativeToVoiceDb,actualBinaryPauseWindow:{startSeconds:Number(pauseStart.toFixed(3)),endSeconds:Number((pauseStart+pauseDuration).toFixed(3)),...musicPauseWindow},actualBinaryPauseMidrange:pauseMidrangeWindow,baseGainDb:audioPlan.music.plannedBaseGainDb,duckDb:audioPlan.music.plannedDuckUnderVoiceDb,fadeInSeconds:audioPlan.music.plannedFadeInSeconds,fadeOutSeconds:audioPlan.music.plannedFadeOutSeconds},sfx:{audible:sfxAudible,cues:sfxCues},voiceQa:'PASS',finalReviewTechnicalQa:'PASS',humanAudioReview:masteringEnabled?'REQUIRED':'NOT_CONFIGURED',delegatedFinalReviewAcceptance:'PENDING',exportHandoffStatus:'BLOCKED',vbeeCalls:0,vbeeCharacters:0};
atomicJson(join(reviewDirectory,'audio-retention-metrics.json'),metrics);atomicJson(reviewSnapshotPath,review);const reviewSnapshotSha=hash(reviewSnapshotPath);const humanReviewLine=masteringEnabled?'\nmastering_policy: CKAI_SHORT_FORM_MASTERING_V1\nhuman_audio_review: REQUIRED':'';atomicWrite(reviewArtifactPath,`---\nid: ${review.id}\ntype: short-form-final-review\nreview_version: ${reviewVersion}\ninput_eligibility: production\nsource_voice_artifact: ${ownerRel(reviewArtifactPath,voiceArtifactPath)}\nsource_voice_artifact_sha256: ${hash(voiceArtifactPath)}\nsource_voice_snapshot: ${ownerRel(reviewArtifactPath,voiceSnapshotPath)}\nsource_voice_snapshot_sha256: ${acceptedVoiceSha}\nsource_voice_preview: ${ownerRel(reviewArtifactPath,voicePreviewPath)}\nsource_voice_preview_sha256: ${acceptedVoicePreviewSha}\nreview_preview: ${ownerRel(reviewArtifactPath,outputPath)}\nreview_preview_sha256: ${review.reviewPreview.sha256}\nreview_snapshot: ${ownerRel(reviewArtifactPath,reviewSnapshotPath)}\nreview_snapshot_sha256: ${reviewSnapshotSha}\ntechnical_review: PASS${humanReviewLine}\nfinal_review: pending\nhuman_decision: pending\nexport_handoff_status: BLOCKED\nunresolved_issues: human audio review and delegated Final Review acceptance pending\noperator_acceptance_by: pending\noperator_acceptance_at: pending\noperator_acceptance_basis: pending\noperator_acceptance_source_sha256: pending\n---\n\n# CKAI-0004 ${reviewVersion} Final Review Candidate\n\nTechnical Review PASS. Human audio review is required. STEP 08 remains blocked until delegated ChatGPT Final Review acceptance is bound to this exact snapshot and ${reviewVersion} review binary.\n`);
console.log(JSON.stringify({status:'PASS',reviewVersion,reviewPreview:review.reviewPreview,reviewSnapshot:rel(reviewSnapshotPath),reviewSnapshotSha256:reviewSnapshotSha,metricsPath:rel(join(reviewDirectory,'audio-retention-metrics.json')),retention,musicActuallyAudible:musicActuallyAudible?'PASS':'FAIL',musicRelativeToVoiceDb,actualMusicPauseWindow:metrics.music.actualBinaryPauseWindow,sfxAudible,semanticSfxBindings:semantic.bindings,meanVolumeDb:experience.meanVolumeDb,maxVolumeDb:experience.maxVolumeDb,integratedLufs,truePeakDbtp,lra,masteringQa,humanAudioReviewRequired:masteringEnabled,clippingResult,step08:'BLOCKED',publishing:'NONE',delegatedFinalReviewAcceptance:'PENDING'},null,2));
