import {readFileSync,renameSync,writeFileSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import {sha256} from '../../voice/src/segment';
import type {VoicePlan} from '../../voice/src/model';
import {inspectActualMix} from '../src/actual-mix';
import type {FinishingAudioAsset} from '../src/model';

const reviewPath=resolve('generated/previews/CKAI-0004-review-v5.1.mp4');const voicePath=resolve('generated/previews/CKAI-0004-voice-v5.mp4');const voicePlanPath=resolve('generated/voice/CKAI-0004/v5/voice-plan.pending.json');const propsPath=resolve('generated/production/CKAI-0004/v5.1/review-props.json');const metricsPath=resolve('generated/review/CKAI-0004/v5.1/audio-retention-metrics.json');const artifactPath=resolve('content/reviews/CKAI-0004_tach-du-kien-suy-luan-chua-biet_final-review-v5.1.md');
const hash=(path:string)=>sha256(readFileSync(path));const expectedReviewSha='2B114B2C212713EB951F87095336567D0C8F185A815853538001BC7A67D331A4';if(hash(reviewPath)!==expectedReviewSha)throw new Error('V5.1 review binary changed before actual-mix revalidation');
const plan=JSON.parse(readFileSync(voicePlanPath,'utf8')) as VoicePlan;const props=JSON.parse(readFileSync(propsPath,'utf8')) as{finishingAudioAssets:FinishingAudioAsset[]};const metrics=JSON.parse(readFileSync(metricsPath,'utf8')) as Record<string,unknown>;
const voiceWindows=plan.segments.map((segment)=>({start:segment.slotStartSeconds,end:segment.slotStartSeconds+(segment.measuredDurationSeconds??segment.slotEndSeconds-segment.slotStartSeconds)}));const sfx=props.finishingAudioAssets.filter((asset)=>asset.type==='sfx');const active=voiceWindows.filter((window)=>window.end-window.start>=1).sort((a,b)=>(b.end-b.start)-(a.end-a.start)).map((window)=>({startSeconds:Number((window.start+(window.end-window.start-1)/2).toFixed(3)),durationSeconds:1})).find((window)=>sfx.every((cue)=>cue.startSeconds+(.2)<window.startSeconds||cue.startSeconds>window.startSeconds+window.durationSeconds));if(!active)throw new Error('No SFX-free active Voice window available');
const pauses=voiceWindows.slice(0,-1).map((window,index)=>({start:window.end,end:voiceWindows[index+1]!.start})).filter((window)=>window.end-window.start>=.7).sort((a,b)=>(b.end-b.start)-(a.end-a.start));const pause=pauses.find((window)=>sfx.every((cue)=>cue.startSeconds<window.start||cue.startSeconds>window.end));if(!pause)throw new Error('No SFX-free pause window available');const pauseWindow={startSeconds:Number((pause.start+.1).toFixed(3)),durationSeconds:Number(Math.min(.9,pause.end-pause.start-.2).toFixed(3))};
const result=inspectActualMix({mixedBinary:reviewPath,voiceBinary:voicePath,activeWindow:active,pauseWindow,cues:sfx.map((cue)=>({id:cue.id,semanticEventSeconds:cue.startSeconds,durationSeconds:cue.durationSeconds??.5}))});if(result.status!=='PASS')throw new Error(`ACTUAL_BINARY_MIX_QA_BLOCKED: ${JSON.stringify(result.checks)}`);
const nextMetrics={...metrics,actualBinaryMixQa:result};const temporary=`${metricsPath}.${process.pid}.tmp`;writeFileSync(temporary,`${JSON.stringify(nextMetrics,null,2)}\n`,'utf8');renameSync(temporary,metricsPath);
let artifact=readFileSync(artifactPath,'utf8');for(const [field,status] of Object.entries(result.checks)){const key=field.toLowerCase();if(!artifact.includes(`${key}:`))artifact=artifact.replace('technical_review: PASS',`technical_review: PASS\n${key}: ${status}`);}const artifactTemp=`${artifactPath}.${process.pid}.tmp`;writeFileSync(artifactTemp,artifact,'utf8');renameSync(artifactTemp,artifactPath);
console.log(JSON.stringify({reviewBinarySha256:expectedReviewSha,...result},null,2));
